<template>
	<div class="wrapper">
		<liquorTree
			v-for="(repoTree, index) in releaseTrees"
			v-bind:key="index"
			:data="repoTree"
			:options="{ checkbox: true }"
			@tree:mounted="onTreeMounted"
			ref="tree"
		/>
	</div>
</template>

<script>
// import LiquroTree from './LiquroTree.vue';
import LiquorTree from 'liquor-tree';

var treeData = [
	{
		text: 'Angular',
		data: {
			name: 'Angular',
			slug: 'angular',
			type: 'angular',
			links: {
				home: 'https://angular.io/',
				code: 'https://github.com/angular/angular',
			},
			version: '',
			release: '5.2.9',
			mtime: 1521396825,
			db_size: 9378792,
			isRoot: true,
		},
		children: [
			{
				text: 'Angular',
				data: {
					name: 'Angular',
					slug: 'angular',
					type: 'angular',
					links: {
						home: 'https://angular.io/',
						code: 'https://github.com/angular/angular',
					},
					version: '',
					release: '5.2.9',
					mtime: 1521396825,
					db_size: 9378792,
				},
			},
			{
				text: 'Angular 4',
				data: {
					name: 'Angular',
					slug: 'angular~4',
					type: 'angular',
					links: {
						home: 'https://angular.io/',
						code: 'https://github.com/angular/angular',
					},
					version: '4',
					release: '4.4.6',
					mtime: 1510333140,
					db_size: 8247972,
				},
			},
			{
				text: 'Angular 2',
				data: {
					name: 'Angular',
					slug: 'angular~2',
					type: 'angular',
					links: {
						home: 'https://angular.io/',
						code: 'https://github.com/angular/angular',
					},
					version: '2',
					release: '2.4.10',
					mtime: 1501435056,
					db_size: 7928892,
				},
			},
		],
	},
	{
		text: 'Angular.js',
		data: {
			name: 'Angular.js',
			slug: 'angularjs~1.6',
			type: 'angularjs',
			version: '1.6',
			release: '1.6.6',
			mtime: 1509291873,
			db_size: 2078695,
			isRoot: true,
		},
		children: [
			{
				text: 'Angular.js 1.6',
				data: {
					name: 'Angular.js',
					slug: 'angularjs~1.6',
					type: 'angularjs',
					version: '1.6',
					release: '1.6.6',
					mtime: 1509291873,
					db_size: 2078695,
				},
			},
			{
				text: 'Angular.js 1.5',
				data: {
					name: 'Angular.js',
					slug: 'angularjs~1.5',
					type: 'angularjs',
					version: '1.5',
					release: '1.5.11',
					mtime: 1501418597,
					db_size: 2034320,
				},
			},
			{
				text: 'Angular.js 1.4',
				data: {
					name: 'Angular.js',
					slug: 'angularjs~1.4',
					type: 'angularjs',
					version: '1.4',
					release: '1.4.14',
					mtime: 1501418614,
					db_size: 1801860,
				},
			},
			{
				text: 'Angular.js 1.3',
				data: {
					name: 'Angular.js',
					slug: 'angularjs~1.3',
					type: 'angularjs',
					version: '1.3',
					release: '1.3.20',
					mtime: 1501418630,
					db_size: 1669877,
				},
			},
			{
				text: 'Angular.js 1.2',
				data: {
					name: 'Angular.js',
					slug: 'angularjs~1.2',
					type: 'angularjs',
					version: '1.2',
					release: '1.2.32',
					mtime: 1501418645,
					db_size: 1362341,
				},
			},
		],
	},
	{
		text: 'Ansible 2.4',
		data: {
			name: 'Ansible',
			slug: 'ansible~2.4',
			type: 'sphinx',
			links: {
				home: 'https://www.ansible.com/',
				code: 'https://github.com/ansible/ansible',
			},
			version: '2.4',
			release: '2.4.3',
			mtime: 1521914994,
			db_size: 12975660,
			isRoot: true,
		},
	},
	{
		text: 'Apache HTTP Server',
		data: {
			name: 'Apache HTTP Server',
			slug: 'apache_http_server',
			type: 'apache',
			links: {
				home: 'https://httpd.apache.org/',
			},
			release: '2.4.29',
			mtime: 1509291942,
			db_size: 3569398,
			isRoot: true,
		},
	},
	{
		text: 'Apache Pig',
		data: {
			name: 'Apache Pig',
			slug: 'apache_pig~0.17',
			type: 'apache_pig',
			links: {
				home: 'https://pig.apache.org/',
			},
			version: '0.17',
			release: '0.17.0',
			mtime: 1498397567,
			db_size: 731436,
			isRoot: true,
		},
		children: [
			{
				text: 'Apache Pig 0.17',
				data: {
					name: 'Apache Pig',
					slug: 'apache_pig~0.17',
					type: 'apache_pig',
					links: {
						home: 'https://pig.apache.org/',
					},
					version: '0.17',
					release: '0.17.0',
					mtime: 1498397567,
					db_size: 731436,
				},
			},
			{
				text: 'Apache Pig 0.16',
				data: {
					name: 'Apache Pig',
					slug: 'apache_pig~0.16',
					type: 'apache_pig',
					links: {
						home: 'https://pig.apache.org/',
					},
					version: '0.16',
					release: '0.16.0',
					mtime: 1469311906,
					db_size: 716644,
				},
			},
			{
				text: 'Apache Pig 0.15',
				data: {
					name: 'Apache Pig',
					slug: 'apache_pig~0.15',
					type: 'apache_pig',
					links: {
						home: 'https://pig.apache.org/',
					},
					version: '0.15',
					release: '0.15.0',
					mtime: 1461510756,
					db_size: 703105,
				},
			},
			{
				text: 'Apache Pig 0.14',
				data: {
					name: 'Apache Pig',
					slug: 'apache_pig~0.14',
					type: 'apache_pig',
					links: {
						home: 'https://pig.apache.org/',
					},
					version: '0.14',
					release: '0.14.0',
					mtime: 1461510759,
					db_size: 697409,
				},
			},
			{
				text: 'Apache Pig 0.13',
				data: {
					name: 'Apache Pig',
					slug: 'apache_pig~0.13',
					type: 'apache_pig',
					links: {
						home: 'https://pig.apache.org/',
					},
					version: '0.13',
					release: '0.13.0',
					mtime: 1461510762,
					db_size: 671261,
				},
			},
		],
	},
	{
		text: 'Async',
		data: {
			name: 'Async',
			slug: 'async',
			type: 'async',
			links: {
				home: 'https://caolan.github.io/async/',
				code: 'https://github.com/caolan/async',
			},
			release: '2.6.0',
			mtime: 1510332635,
			db_size: 207425,
			isRoot: true,
		},
	},
	{
		text: 'Babel',
		data: {
			name: 'Babel',
			slug: 'babel',
			type: 'simple',
			links: {
				home: 'https://babeljs.io/',
				code: 'https://github.com/babel/babel',
			},
			release: '6.26.1',
			mtime: 1517763345,
			db_size: 371969,
			isRoot: true,
		},
	},
	{
		text: 'Backbone.js',
		data: {
			name: 'Backbone.js',
			slug: 'backbone',
			type: 'underscore',
			links: {
				home: 'http://backbonejs.org/',
				code: 'https://github.com/jashkenas/backbone',
			},
			release: '1.3.3',
			mtime: 1460208458,
			db_size: 84906,
			isRoot: true,
		},
	},
	{
		text: 'Bluebird',
		data: {
			name: 'Bluebird',
			slug: 'bluebird',
			type: 'simple',
			links: {
				home: 'http://bluebirdjs.com/',
				code: 'https://github.com/petkaantonov/bluebird/',
			},
			release: '3.5.1',
			mtime: 1511735064,
			db_size: 444684,
			isRoot: true,
		},
	},
	{
		text: 'Bootstrap',
		data: {
			name: 'Bootstrap',
			slug: 'bootstrap~4',
			type: 'bootstrap',
			links: {
				home: 'https://getbootstrap.com/',
				code: 'https://github.com/twbs/bootstrap',
			},
			version: '4',
			release: '4.0.0',
			mtime: 1517182812,
			db_size: 676401,
			isRoot: true,
		},
		children: [
			{
				text: 'Bootstrap 4',
				data: {
					name: 'Bootstrap',
					slug: 'bootstrap~4',
					type: 'bootstrap',
					links: {
						home: 'https://getbootstrap.com/',
						code: 'https://github.com/twbs/bootstrap',
					},
					version: '4',
					release: '4.0.0',
					mtime: 1517182812,
					db_size: 676401,
				},
			},
			{
				text: 'Bootstrap 3',
				data: {
					name: 'Bootstrap',
					slug: 'bootstrap~3',
					type: 'bootstrap',
					links: {
						home: 'https://getbootstrap.com/',
						code: 'https://github.com/twbs/bootstrap',
					},
					version: '3',
					release: '3.3.7',
					mtime: 1511736590,
					db_size: 1692281,
				},
			},
		],
	},
	{
		text: 'Bottle',
		data: {
			name: 'Bottle',
			slug: 'bottle~0.12',
			type: 'sphinx',
			links: {
				home: 'https://bottlepy.org/',
				code: 'https://github.com/bottlepy/bottle',
			},
			version: '0.12',
			release: '0.12.13',
			mtime: 1484519567,
			db_size: 299543,
			isRoot: true,
		},
		children: [
			{
				text: 'Bottle 0.12',
				data: {
					name: 'Bottle',
					slug: 'bottle~0.12',
					type: 'sphinx',
					links: {
						home: 'https://bottlepy.org/',
						code: 'https://github.com/bottlepy/bottle',
					},
					version: '0.12',
					release: '0.12.13',
					mtime: 1484519567,
					db_size: 299543,
				},
			},
			{
				text: 'Bottle 0.11',
				data: {
					name: 'Bottle',
					slug: 'bottle~0.11',
					type: 'sphinx',
					links: {
						home: 'https://bottlepy.org/',
						code: 'https://github.com/bottlepy/bottle',
					},
					version: '0.11',
					release: '0.11.7',
					mtime: 1484519569,
					db_size: 274880,
				},
			},
		],
	},
	{
		text: 'Bower',
		data: {
			name: 'Bower',
			slug: 'bower',
			type: 'bower',
			links: {
				home: 'https://bower.io/',
				code: 'https://github.com/bower/bower',
			},
			release: '1.8.2',
			mtime: 1505656456,
			db_size: 46302,
			isRoot: true,
		},
	},
	{
		text: 'C',
		data: {
			name: 'C',
			slug: 'c',
			type: 'c',
			mtime: 1521903579,
			db_size: 3831357,
			isRoot: true,
		},
	},
	{
		text: 'C++',
		data: {
			name: 'C++',
			slug: 'cpp',
			type: 'c',
			mtime: 1521903410,
			db_size: 21391403,
			isRoot: true,
		},
	},
	{
		text: 'CakePHP',
		data: {
			name: 'CakePHP',
			slug: 'cakephp~3.5',
			type: 'cakephp',
			links: {
				home: 'https://cakephp.org/',
				code: 'https://github.com/cakephp/cakephp',
			},
			version: '3.5',
			release: '3.5.2',
			mtime: 1506274065,
			db_size: 10656207,
			isRoot: true,
		},
		children: [
			{
				text: 'CakePHP 3.5',
				data: {
					name: 'CakePHP',
					slug: 'cakephp~3.5',
					type: 'cakephp',
					links: {
						home: 'https://cakephp.org/',
						code: 'https://github.com/cakephp/cakephp',
					},
					version: '3.5',
					release: '3.5.2',
					mtime: 1506274065,
					db_size: 10656207,
				},
			},
			{
				text: 'CakePHP 3.4',
				data: {
					name: 'CakePHP',
					slug: 'cakephp~3.4',
					type: 'cakephp',
					links: {
						home: 'https://cakephp.org/',
						code: 'https://github.com/cakephp/cakephp',
					},
					version: '3.4',
					release: '3.4.13',
					mtime: 1503758159,
					db_size: 10562123,
				},
			},
			{
				text: 'CakePHP 3.3',
				data: {
					name: 'CakePHP',
					slug: 'cakephp~3.3',
					type: 'cakephp',
					links: {
						home: 'https://cakephp.org/',
						code: 'https://github.com/cakephp/cakephp',
					},
					version: '3.3',
					release: '3.3.15',
					mtime: 1487425686,
					db_size: 8700321,
				},
			},
			{
				text: 'CakePHP 3.2',
				data: {
					name: 'CakePHP',
					slug: 'cakephp~3.2',
					type: 'cakephp',
					links: {
						home: 'https://cakephp.org/',
						code: 'https://github.com/cakephp/cakephp',
					},
					version: '3.2',
					release: '3.2.14',
					mtime: 1474125449,
					db_size: 8263596,
				},
			},
			{
				text: 'CakePHP 3.1',
				data: {
					name: 'CakePHP',
					slug: 'cakephp~3.1',
					type: 'cakephp',
					links: {
						home: 'https://cakephp.org/',
						code: 'https://github.com/cakephp/cakephp',
					},
					version: '3.1',
					release: '3.1.13',
					mtime: 1462111394,
					db_size: 7959275,
				},
			},
			{
				text: 'CakePHP 2.10',
				data: {
					name: 'CakePHP',
					slug: 'cakephp~2.10',
					type: 'cakephp',
					links: {
						home: 'https://cakephp.org/',
						code: 'https://github.com/cakephp/cakephp',
					},
					version: '2.10',
					release: '2.10.3',
					mtime: 1506274147,
					db_size: 6138877,
				},
			},
			{
				text: 'CakePHP 2.9',
				data: {
					name: 'CakePHP',
					slug: 'cakephp~2.9',
					type: 'cakephp',
					links: {
						home: 'https://cakephp.org/',
						code: 'https://github.com/cakephp/cakephp',
					},
					version: '2.9',
					release: '2.9.4',
					mtime: 1484523236,
					db_size: 5552668,
				},
			},
			{
				text: 'CakePHP 2.8',
				data: {
					name: 'CakePHP',
					slug: 'cakephp~2.8',
					type: 'cakephp',
					links: {
						home: 'https://cakephp.org/',
						code: 'https://github.com/cakephp/cakephp',
					},
					version: '2.8',
					release: '2.8.8',
					mtime: 1474125323,
					db_size: 7518979,
				},
			},
			{
				text: 'CakePHP 2.7',
				data: {
					name: 'CakePHP',
					slug: 'cakephp~2.7',
					type: 'cakephp',
					links: {
						home: 'https://cakephp.org/',
						code: 'https://github.com/cakephp/cakephp',
					},
					version: '2.7',
					release: '2.7.11',
					mtime: 1462111536,
					db_size: 8483870,
				},
			},
		],
	},
	{
		text: 'Chai',
		data: {
			name: 'Chai',
			slug: 'chai',
			type: 'chai',
			links: {
				home: 'http://chaijs.com/',
				code: 'https://github.com/chaijs/chai',
			},
			release: '4.1.0',
			mtime: 1500290759,
			db_size: 394800,
			isRoot: true,
		},
	},
	{
		text: 'Chef',
		data: {
			name: 'Chef',
			slug: 'chef~12',
			type: 'sphinx_simple',
			links: {
				home: 'https://www.chef.io/',
				code: 'https://github.com/chef/chef',
			},
			version: '12',
			release: '12.13',
			mtime: 1495472987,
			db_size: 3833180,
			isRoot: true,
		},
		children: [
			{
				text: 'Chef 12',
				data: {
					name: 'Chef',
					slug: 'chef~12',
					type: 'sphinx_simple',
					links: {
						home: 'https://www.chef.io/',
						code: 'https://github.com/chef/chef',
					},
					version: '12',
					release: '12.13',
					mtime: 1495472987,
					db_size: 3833180,
				},
			},
			{
				text: 'Chef 11',
				data: {
					name: 'Chef',
					slug: 'chef~11',
					type: 'sphinx_simple',
					links: {
						home: 'https://www.chef.io/',
						code: 'https://github.com/chef/chef',
					},
					version: '11',
					release: '11.18',
					mtime: 1495473070,
					db_size: 3436869,
				},
			},
		],
	},
	{
		text: 'Clojure',
		data: {
			name: 'Clojure',
			slug: 'clojure~1.9',
			type: 'clojure',
			version: '1.9',
			release: '1.9',
			mtime: 1515366982,
			db_size: 551767,
			isRoot: true,
		},
		children: [
			{
				text: 'Clojure 1.9',
				data: {
					name: 'Clojure',
					slug: 'clojure~1.9',
					type: 'clojure',
					version: '1.9',
					release: '1.9',
					mtime: 1515366982,
					db_size: 551767,
				},
			},
			{
				text: 'Clojure 1.8',
				data: {
					name: 'Clojure',
					slug: 'clojure~1.8',
					type: 'clojure',
					version: '1.8',
					release: '1.8',
					mtime: 1453669840,
					db_size: 534449,
				},
			},
			{
				text: 'Clojure 1.7',
				data: {
					name: 'Clojure',
					slug: 'clojure~1.7',
					type: 'clojure',
					version: '1.7',
					release: '1.7',
					mtime: 1453669823,
					db_size: 525307,
				},
			},
		],
	},
	{
		text: 'CMake',
		data: {
			name: 'CMake',
			slug: 'cmake~3.10',
			type: 'sphinx_simple',
			links: {
				home: 'https://cmake.org/',
				code: 'https://cmake.org/gitweb?p=cmake.git;a=summary',
			},
			version: '3.10',
			release: '3.10.1',
			mtime: 1515367134,
			db_size: 3260352,
			isRoot: true,
		},
		children: [
			{
				text: 'CMake 3.10',
				data: {
					name: 'CMake',
					slug: 'cmake~3.10',
					type: 'sphinx_simple',
					links: {
						home: 'https://cmake.org/',
						code: 'https://cmake.org/gitweb?p=cmake.git;a=summary',
					},
					version: '3.10',
					release: '3.10.1',
					mtime: 1515367134,
					db_size: 3260352,
				},
			},
			{
				text: 'CMake 3.9',
				data: {
					name: 'CMake',
					slug: 'cmake~3.9',
					type: 'sphinx_simple',
					links: {
						home: 'https://cmake.org/',
						code: 'https://cmake.org/gitweb?p=cmake.git;a=summary',
					},
					version: '3.9',
					release: '3.9.6',
					mtime: 1515367068,
					db_size: 3094540,
				},
			},
			{
				text: 'CMake 3.8',
				data: {
					name: 'CMake',
					slug: 'cmake~3.8',
					type: 'sphinx_simple',
					links: {
						home: 'https://cmake.org/',
						code: 'https://cmake.org/gitweb?p=cmake.git;a=summary',
					},
					version: '3.8',
					release: '3.8.2',
					mtime: 1500742171,
					db_size: 2975592,
				},
			},
			{
				text: 'CMake 3.7',
				data: {
					name: 'CMake',
					slug: 'cmake~3.7',
					type: 'sphinx_simple',
					links: {
						home: 'https://cmake.org/',
						code: 'https://cmake.org/gitweb?p=cmake.git;a=summary',
					},
					version: '3.7',
					release: '3.7.2',
					mtime: 1492960254,
					db_size: 2866766,
				},
			},
			{
				text: 'CMake 3.6',
				data: {
					name: 'CMake',
					slug: 'cmake~3.6',
					type: 'sphinx_simple',
					links: {
						home: 'https://cmake.org/',
						code: 'https://cmake.org/gitweb?p=cmake.git;a=summary',
					},
					version: '3.6',
					release: '3.6.3',
					mtime: 1479055624,
					db_size: 2727425,
				},
			},
			{
				text: 'CMake 3.5',
				data: {
					name: 'CMake',
					slug: 'cmake~3.5',
					type: 'sphinx_simple',
					links: {
						home: 'https://cmake.org/',
						code: 'https://cmake.org/gitweb?p=cmake.git;a=summary',
					},
					version: '3.5',
					release: '3.5.2',
					mtime: 1467561510,
					db_size: 2656199,
				},
			},
		],
	},
	{
		text: 'Codeception',
		data: {
			name: 'Codeception',
			slug: 'codeception',
			type: 'codeception',
			links: {
				home: 'https://codeception.com/',
				code: 'https://github.com/codeception/codeception',
			},
			release: '2.4.0',
			mtime: 1521386083,
			db_size: 1601844,
			isRoot: true,
		},
	},
	{
		text: 'CodeceptJS',
		data: {
			name: 'CodeceptJS',
			slug: 'codeceptjs',
			type: 'codeceptjs',
			links: {
				home: 'https://codecept.io/',
				code: 'https://github.com/codeception/codeceptjs',
			},
			release: '1.1.7',
			mtime: 1521386248,
			db_size: 482861,
			isRoot: true,
		},
	},
	{
		text: 'CodeIgniter 3',
		data: {
			name: 'CodeIgniter',
			slug: 'codeigniter~3',
			type: 'sphinx',
			links: {
				home: 'https://codeigniter.com/',
				code: 'https://github.com/bcit-ci/CodeIgniter',
			},
			version: '3',
			release: '3.1.8',
			mtime: 1521915543,
			db_size: 1383667,
			isRoot: true,
		},
	},
	{
		text: 'CoffeeScript',
		data: {
			name: 'CoffeeScript',
			slug: 'coffeescript~2',
			type: 'coffeescript',
			links: {
				home: 'http://coffeescript.org',
				code: 'https://github.com/jashkenas/coffeescript',
			},
			version: '2',
			release: '2.2.2',
			mtime: 1519570648,
			db_size: 109309,
			isRoot: true,
		},
		children: [
			{
				text: 'CoffeeScript 2',
				data: {
					name: 'CoffeeScript',
					slug: 'coffeescript~2',
					type: 'coffeescript',
					links: {
						home: 'http://coffeescript.org',
						code: 'https://github.com/jashkenas/coffeescript',
					},
					version: '2',
					release: '2.2.2',
					mtime: 1519570648,
					db_size: 109309,
				},
			},
			{
				text: 'CoffeeScript 1',
				data: {
					name: 'CoffeeScript',
					slug: 'coffeescript~1',
					type: 'coffeescript',
					links: {
						home: 'http://coffeescript.org',
						code: 'https://github.com/jashkenas/coffeescript',
					},
					version: '1',
					release: '1.12.6',
					mtime: 1507562899,
					db_size: 66981,
				},
			},
		],
	},
	{
		text: 'Cordova',
		data: {
			name: 'Cordova',
			slug: 'cordova~7',
			type: 'cordova',
			links: {
				home: 'https://cordova.apache.org/',
				code: 'https://git-wip-us.apache.org/repos/asf/cordova-cli.git',
			},
			version: '7',
			release: '7.1.0',
			mtime: 1509299994,
			db_size: 2558161,
			isRoot: true,
		},
		children: [
			{
				text: 'Cordova 7',
				data: {
					name: 'Cordova',
					slug: 'cordova~7',
					type: 'cordova',
					links: {
						home: 'https://cordova.apache.org/',
						code: 'https://git-wip-us.apache.org/repos/asf/cordova-cli.git',
					},
					version: '7',
					release: '7.1.0',
					mtime: 1509299994,
					db_size: 2558161,
				},
			},
			{
				text: 'Cordova 6',
				data: {
					name: 'Cordova',
					slug: 'cordova~6',
					type: 'cordova',
					links: {
						home: 'https://cordova.apache.org/',
						code: 'https://git-wip-us.apache.org/repos/asf/cordova-cli.git',
					},
					version: '6',
					release: '6.5.0',
					mtime: 1506274282,
					db_size: 2536890,
				},
			},
		],
	},
	{
		text: 'Crystal',
		data: {
			name: 'Crystal',
			slug: 'crystal',
			type: 'crystal',
			links: {
				home: 'https://crystal-lang.org/',
				code: 'https://github.com/crystal-lang/crystal',
			},
			release: '0.24.1',
			mtime: 1515367561,
			db_size: 9170378,
			isRoot: true,
		},
	},
	{
		text: 'CSS',
		data: {
			name: 'CSS',
			slug: 'css',
			type: 'mdn',
			mtime: 1521409118,
			db_size: 10271796,
			isRoot: true,
		},
	},
	{
		text: 'D',
		data: {
			name: 'D',
			slug: 'd',
			type: 'd',
			links: {
				home: 'https://dlang.org/',
				code: 'https://github.com/dlang/phobos',
			},
			release: '2.079.0',
			mtime: 1521386521,
			db_size: 5564723,
			isRoot: true,
		},
	},
	{
		text: 'D3.js',
		data: {
			name: 'D3.js',
			slug: 'd3~4',
			type: 'd3',
			links: {
				home: 'https://d3js.org/',
				code: 'https://github.com/d3/d3',
			},
			version: '4',
			release: '4.12.2',
			mtime: 1515367749,
			db_size: 13601596,
			isRoot: true,
		},
		children: [
			{
				text: 'D3.js 4',
				data: {
					name: 'D3.js',
					slug: 'd3~4',
					type: 'd3',
					links: {
						home: 'https://d3js.org/',
						code: 'https://github.com/d3/d3',
					},
					version: '4',
					release: '4.12.2',
					mtime: 1515367749,
					db_size: 13601596,
				},
			},
			{
				text: 'D3.js 3',
				data: {
					name: 'D3.js',
					slug: 'd3~3',
					type: 'd3',
					links: {
						home: 'https://d3js.org/',
						code: 'https://github.com/d3/d3',
					},
					version: '3',
					release: '3.5.17',
					mtime: 1472313914,
					db_size: 653806,
				},
			},
		],
	},
	{
		text: 'Django',
		data: {
			name: 'Django',
			slug: 'django~2.0',
			type: 'sphinx',
			links: {
				home: 'https://www.djangoproject.com/',
				code: 'https://github.com/django/django',
			},
			version: '2.0',
			release: '2.0.2',
			mtime: 1519585673,
			db_size: 6068899,
			isRoot: true,
		},
		children: [
			{
				text: 'Django 2.0',
				data: {
					name: 'Django',
					slug: 'django~2.0',
					type: 'sphinx',
					links: {
						home: 'https://www.djangoproject.com/',
						code: 'https://github.com/django/django',
					},
					version: '2.0',
					release: '2.0.2',
					mtime: 1519585673,
					db_size: 6068899,
				},
			},
			{
				text: 'Django 1.11',
				data: {
					name: 'Django',
					slug: 'django~1.11',
					type: 'sphinx',
					links: {
						home: 'https://www.djangoproject.com/',
						code: 'https://github.com/django/django',
					},
					version: '1.11',
					release: '1.11.9',
					mtime: 1515954092,
					db_size: 6145924,
				},
			},
			{
				text: 'Django 1.10',
				data: {
					name: 'Django',
					slug: 'django~1.10',
					type: 'sphinx',
					links: {
						home: 'https://www.djangoproject.com/',
						code: 'https://github.com/django/django',
					},
					version: '1.10',
					release: '1.10.8',
					mtime: 1505055496,
					db_size: 6007190,
				},
			},
			{
				text: 'Django 1.9',
				data: {
					name: 'Django',
					slug: 'django~1.9',
					type: 'sphinx',
					links: {
						home: 'https://www.djangoproject.com/',
						code: 'https://github.com/django/django',
					},
					version: '1.9',
					release: '1.9.13',
					mtime: 1491762860,
					db_size: 5396651,
				},
			},
			{
				text: 'Django 1.8',
				data: {
					name: 'Django',
					slug: 'django~1.8',
					type: 'sphinx',
					links: {
						home: 'https://www.djangoproject.com/',
						code: 'https://github.com/django/django',
					},
					version: '1.8',
					release: '1.8.18',
					mtime: 1491762906,
					db_size: 5201532,
				},
			},
		],
	},
	{
		text: 'Docker',
		data: {
			name: 'Docker',
			slug: 'docker~17',
			type: 'docker',
			links: {
				home: 'https://docker.com/',
				code: 'https://github.com/docker/docker',
			},
			version: '17',
			release: '17.06',
			mtime: 1504541210,
			db_size: 7538709,
			isRoot: true,
		},
		children: [
			{
				text: 'Docker 17',
				data: {
					name: 'Docker',
					slug: 'docker~17',
					type: 'docker',
					links: {
						home: 'https://docker.com/',
						code: 'https://github.com/docker/docker',
					},
					version: '17',
					release: '17.06',
					mtime: 1504541210,
					db_size: 7538709,
				},
			},
			{
				text: 'Docker 1.13',
				data: {
					name: 'Docker',
					slug: 'docker~1.13',
					type: 'docker',
					links: {
						home: 'https://docker.com/',
						code: 'https://github.com/docker/docker',
					},
					version: '1.13',
					release: '1.13',
					mtime: 1504538357,
					db_size: 6967276,
				},
			},
			{
				text: 'Docker 1.12',
				data: {
					name: 'Docker',
					slug: 'docker~1.12',
					type: 'docker',
					links: {
						home: 'https://docker.com/',
						code: 'https://github.com/docker/docker',
					},
					version: '1.12',
					release: '1.12',
					mtime: 1504538249,
					db_size: 6667872,
				},
			},
			{
				text: 'Docker 1.11',
				data: {
					name: 'Docker',
					slug: 'docker~1.11',
					type: 'docker',
					links: {
						home: 'https://docker.com/',
						code: 'https://github.com/docker/docker',
					},
					version: '1.11',
					release: '1.11',
					mtime: 1504538129,
					db_size: 5827804,
				},
			},
			{
				text: 'Docker 1.10',
				data: {
					name: 'Docker',
					slug: 'docker~1.10',
					type: 'docker',
					links: {
						home: 'https://docker.com/',
						code: 'https://github.com/docker/docker',
					},
					version: '1.10',
					release: '1.10',
					mtime: 1504538058,
					db_size: 7125854,
				},
			},
		],
	},
	{
		text: 'Dojo',
		data: {
			name: 'Dojo',
			slug: 'dojo',
			type: 'dojo',
			links: {
				home: 'http://dojotoolkit.org',
				code: 'https://github.com/dojo/dojo',
			},
			release: '1.10',
			mtime: 1500741465,
			db_size: 2007352,
			isRoot: true,
		},
	},
	{
		text: 'DOM',
		data: {
			name: 'DOM',
			slug: 'dom',
			type: 'mdn',
			mtime: 1521420853,
			db_size: 28424896,
			isRoot: true,
		},
	},
	{
		text: 'DOM Events',
		data: {
			name: 'DOM Events',
			slug: 'dom_events',
			type: 'mdn',
			mtime: 1521400686,
			db_size: 1615020,
			isRoot: true,
		},
	},
	{
		text: 'Drupal',
		data: {
			name: 'Drupal',
			slug: 'drupal~8',
			type: 'drupal',
			links: {
				home: 'https://www.drupal.org/',
				code: 'http://cgit.drupalcode.org/drupal',
			},
			version: '8',
			release: '8.1.7',
			mtime: 1469287435,
			db_size: 37442060,
			isRoot: true,
		},
		children: [
			{
				text: 'Drupal 8',
				data: {
					name: 'Drupal',
					slug: 'drupal~8',
					type: 'drupal',
					links: {
						home: 'https://www.drupal.org/',
						code: 'http://cgit.drupalcode.org/drupal',
					},
					version: '8',
					release: '8.1.7',
					mtime: 1469287435,
					db_size: 37442060,
				},
			},
			{
				text: 'Drupal 7',
				data: {
					name: 'Drupal',
					slug: 'drupal~7',
					type: 'drupal',
					links: {
						home: 'https://www.drupal.org/',
						code: 'http://cgit.drupalcode.org/drupal',
					},
					version: '7',
					release: '7.50',
					mtime: 1468189926,
					db_size: 17249491,
				},
			},
		],
	},
	{
		text: 'Electron',
		data: {
			name: 'Electron',
			slug: 'electron',
			type: 'electron',
			links: {
				home: 'https://electronjs.org/',
				code: 'https://github.com/electron/electron',
			},
			release: '1.8.4',
			mtime: 1521387245,
			db_size: 1661542,
			isRoot: true,
		},
	},
	{
		text: 'Elixir',
		data: {
			name: 'Elixir',
			slug: 'elixir~1.6',
			type: 'elixir',
			links: {
				home: 'https://elixir-lang.org/',
				code: 'https://github.com/elixir-lang/elixir',
			},
			version: '1.6',
			release: '1.6.4',
			mtime: 1521387206,
			db_size: 2891895,
			isRoot: true,
		},
		children: [
			{
				text: 'Elixir 1.6',
				data: {
					name: 'Elixir',
					slug: 'elixir~1.6',
					type: 'elixir',
					links: {
						home: 'https://elixir-lang.org/',
						code: 'https://github.com/elixir-lang/elixir',
					},
					version: '1.6',
					release: '1.6.4',
					mtime: 1521387206,
					db_size: 2891895,
				},
			},
			{
				text: 'Elixir 1.5',
				data: {
					name: 'Elixir',
					slug: 'elixir~1.5',
					type: 'elixir',
					links: {
						home: 'https://elixir-lang.org/',
						code: 'https://github.com/elixir-lang/elixir',
					},
					version: '1.5',
					release: '1.5.3',
					mtime: 1517182992,
					db_size: 2558961,
				},
			},
			{
				text: 'Elixir 1.4',
				data: {
					name: 'Elixir',
					slug: 'elixir~1.4',
					type: 'elixir',
					links: {
						home: 'https://elixir-lang.org/',
						code: 'https://github.com/elixir-lang/elixir',
					},
					version: '1.4',
					release: '1.4.5',
					mtime: 1498397999,
					db_size: 2336862,
				},
			},
			{
				text: 'Elixir 1.3',
				data: {
					name: 'Elixir',
					slug: 'elixir~1.3',
					type: 'elixir',
					links: {
						home: 'https://elixir-lang.org/',
						code: 'https://github.com/elixir-lang/elixir',
					},
					version: '1.3',
					release: '1.3.4',
					mtime: 1495463739,
					db_size: 2113680,
				},
			},
		],
	},
	{
		text: 'Ember.js',
		data: {
			name: 'Ember.js',
			slug: 'ember',
			type: 'ember',
			links: {
				home: 'https://emberjs.com/',
				code: 'https://github.com/emberjs/ember.js',
			},
			release: '2.15.0',
			mtime: 1509308649,
			db_size: 5540495,
			isRoot: true,
		},
	},
	{
		text: 'Erlang',
		data: {
			name: 'Erlang',
			slug: 'erlang~20',
			type: 'erlang',
			links: {
				home: 'https://www.erlang.org/',
				code: 'https://github.com/erlang/otp',
			},
			version: '20',
			release: '20.2',
			mtime: 1519585859,
			db_size: 8856196,
			isRoot: true,
		},
		children: [
			{
				text: 'Erlang 20',
				data: {
					name: 'Erlang',
					slug: 'erlang~20',
					type: 'erlang',
					links: {
						home: 'https://www.erlang.org/',
						code: 'https://github.com/erlang/otp',
					},
					version: '20',
					release: '20.2',
					mtime: 1519585859,
					db_size: 8856196,
				},
			},
			{
				text: 'Erlang 19',
				data: {
					name: 'Erlang',
					slug: 'erlang~19',
					type: 'erlang',
					links: {
						home: 'https://www.erlang.org/',
						code: 'https://github.com/erlang/otp',
					},
					version: '19',
					release: '19.3',
					mtime: 1495487321,
					db_size: 9477458,
				},
			},
			{
				text: 'Erlang 18',
				data: {
					name: 'Erlang',
					slug: 'erlang~18',
					type: 'erlang',
					links: {
						home: 'https://www.erlang.org/',
						code: 'https://github.com/erlang/otp',
					},
					version: '18',
					release: '18.3',
					mtime: 1495487381,
					db_size: 8909158,
				},
			},
		],
	},
	{
		text: 'ESLint',
		data: {
			name: 'ESLint',
			slug: 'eslint',
			type: 'simple',
			links: {
				home: 'https://eslint.org/',
				code: 'https://github.com/eslint/eslint',
			},
			release: '4.19.0',
			mtime: 1521387863,
			db_size: 2018268,
			isRoot: true,
		},
	},
	{
		text: 'Express',
		data: {
			name: 'Express',
			slug: 'express',
			type: 'express',
			links: {
				home: 'http://expressjs.com/',
				code: 'https://github.com/strongloop/express/',
			},
			release: '4.16.1',
			mtime: 1507390010,
			db_size: 322413,
			isRoot: true,
		},
	},
	{
		text: 'Falcon',
		data: {
			name: 'Falcon',
			slug: 'falcon~1.4',
			type: 'sphinx',
			links: {
				home: 'https://falconframework.org/',
				code: 'https://github.com/falconry/falcon',
			},
			version: '1.4',
			release: '1.4.1',
			mtime: 1519571975,
			db_size: 545288,
			isRoot: true,
		},
		children: [
			{
				text: 'Falcon 1.4',
				data: {
					name: 'Falcon',
					slug: 'falcon~1.4',
					type: 'sphinx',
					links: {
						home: 'https://falconframework.org/',
						code: 'https://github.com/falconry/falcon',
					},
					version: '1.4',
					release: '1.4.1',
					mtime: 1519571975,
					db_size: 545288,
				},
			},
			{
				text: 'Falcon 1.3',
				data: {
					name: 'Falcon',
					slug: 'falcon~1.3',
					type: 'sphinx',
					links: {
						home: 'https://falconframework.org/',
						code: 'https://github.com/falconry/falcon',
					},
					version: '1.3',
					release: '1.3.0',
					mtime: 1505055855,
					db_size: 499126,
				},
			},
			{
				text: 'Falcon 1.2',
				data: {
					name: 'Falcon',
					slug: 'falcon~1.2',
					type: 'sphinx',
					links: {
						home: 'https://falconframework.org/',
						code: 'https://github.com/falconry/falcon',
					},
					version: '1.2',
					release: '1.2.0',
					mtime: 1505055858,
					db_size: 442298,
				},
			},
		],
	},
	{
		text: 'Fish',
		data: {
			name: 'Fish',
			slug: 'fish~2.7',
			type: 'fish',
			links: {
				home: 'https://fishshell.com/',
				code: 'https://github.com/fish-shell/fish-shell',
			},
			version: '2.7',
			release: '2.7.1',
			mtime: 1515367841,
			db_size: 336043,
			isRoot: true,
		},
		children: [
			{
				text: 'Fish 2.7',
				data: {
					name: 'Fish',
					slug: 'fish~2.7',
					type: 'fish',
					links: {
						home: 'https://fishshell.com/',
						code: 'https://github.com/fish-shell/fish-shell',
					},
					version: '2.7',
					release: '2.7.1',
					mtime: 1515367841,
					db_size: 336043,
				},
			},
			{
				text: 'Fish 2.6',
				data: {
					name: 'Fish',
					slug: 'fish~2.6',
					type: 'fish',
					links: {
						home: 'https://fishshell.com/',
						code: 'https://github.com/fish-shell/fish-shell',
					},
					version: '2.6',
					release: '2.6.0',
					mtime: 1501448153,
					db_size: 300968,
				},
			},
			{
				text: 'Fish 2.5',
				data: {
					name: 'Fish',
					slug: 'fish~2.5',
					type: 'fish',
					links: {
						home: 'https://fishshell.com/',
						code: 'https://github.com/fish-shell/fish-shell',
					},
					version: '2.5',
					release: '2.5.0',
					mtime: 1486329214,
					db_size: 287843,
				},
			},
			{
				text: 'Fish 2.4',
				data: {
					name: 'Fish',
					slug: 'fish~2.4',
					type: 'fish',
					links: {
						home: 'https://fishshell.com/',
						code: 'https://github.com/fish-shell/fish-shell',
					},
					version: '2.4',
					release: '2.4.0',
					mtime: 1479050136,
					db_size: 282800,
				},
			},
			{
				text: 'Fish 2.3',
				data: {
					name: 'Fish',
					slug: 'fish~2.3',
					type: 'fish',
					links: {
						home: 'https://fishshell.com/',
						code: 'https://github.com/fish-shell/fish-shell',
					},
					version: '2.3',
					release: '2.3.1',
					mtime: 1473109691,
					db_size: 267217,
				},
			},
			{
				text: 'Fish 2.2',
				data: {
					name: 'Fish',
					slug: 'fish~2.2',
					type: 'fish',
					links: {
						home: 'https://fishshell.com/',
						code: 'https://github.com/fish-shell/fish-shell',
					},
					version: '2.2',
					release: '2.2.0',
					mtime: 1473109693,
					db_size: 233348,
				},
			},
		],
	},
	{
		text: 'Flow',
		data: {
			name: 'Flow',
			slug: 'flow',
			type: 'flow',
			links: {
				home: 'https://flow.org/',
				code: 'https://github.com/facebook/flow',
			},
			release: '0.68.0',
			mtime: 1521387140,
			db_size: 321159,
			isRoot: true,
		},
	},
	{
		text: 'GCC',
		data: {
			name: 'GCC',
			slug: 'gcc~7',
			type: 'gnu',
			links: {
				home: 'https://gcc.gnu.org/',
			},
			version: '7',
			release: '7.3.0',
			mtime: 1519585911,
			db_size: 2942101,
			isRoot: true,
		},
		children: [
			{
				text: 'GCC 7',
				data: {
					name: 'GCC',
					slug: 'gcc~7',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/',
					},
					version: '7',
					release: '7.3.0',
					mtime: 1519585911,
					db_size: 2942101,
				},
			},
			{
				text: 'GCC 7 CPP',
				data: {
					name: 'GCC',
					slug: 'gcc~7_cpp',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/',
					},
					version: '7 CPP',
					release: '7.3.0',
					mtime: 1519585917,
					db_size: 293216,
				},
			},
			{
				text: 'GCC 6',
				data: {
					name: 'GCC',
					slug: 'gcc~6',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/',
					},
					version: '6',
					release: '6.4.0',
					mtime: 1503759853,
					db_size: 2802192,
				},
			},
			{
				text: 'GCC 6 CPP',
				data: {
					name: 'GCC',
					slug: 'gcc~6_cpp',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/',
					},
					version: '6 CPP',
					release: '6.4.0',
					mtime: 1503759843,
					db_size: 309058,
				},
			},
			{
				text: 'GCC 5',
				data: {
					name: 'GCC',
					slug: 'gcc~5',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/',
					},
					version: '5',
					release: '5.4.0',
					mtime: 1477863857,
					db_size: 2361957,
				},
			},
			{
				text: 'GCC 5 CPP',
				data: {
					name: 'GCC',
					slug: 'gcc~5_cpp',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/',
					},
					version: '5 CPP',
					release: '5.4.0',
					mtime: 1477863912,
					db_size: 265289,
				},
			},
			{
				text: 'GCC 4',
				data: {
					name: 'GCC',
					slug: 'gcc~4',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/',
					},
					version: '4',
					release: '4.9.3',
					mtime: 1460317637,
					db_size: 2647145,
				},
			},
			{
				text: 'GCC 4 CPP',
				data: {
					name: 'GCC',
					slug: 'gcc~4_cpp',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/',
					},
					version: '4 CPP',
					release: '4.9.3',
					mtime: 1460317638,
					db_size: 265317,
				},
			},
		],
	},
	{
		text: 'Git',
		data: {
			name: 'Git',
			slug: 'git',
			type: 'git',
			links: {
				home: 'https://git-scm.com/',
				code: 'https://github.com/git/git',
			},
			release: '2.16.2',
			mtime: 1519572293,
			db_size: 3152419,
			isRoot: true,
		},
	},
	{
		text: 'GNU Fortran',
		data: {
			name: 'GNU Fortran',
			slug: 'gnu_fortran~7',
			type: 'gnu',
			links: {
				home: 'https://gcc.gnu.org/fortran/',
			},
			version: '7',
			release: '7.3.0',
			mtime: 1519585935,
			db_size: 1250341,
			isRoot: true,
		},
		children: [
			{
				text: 'GNU Fortran 7',
				data: {
					name: 'GNU Fortran',
					slug: 'gnu_fortran~7',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/fortran/',
					},
					version: '7',
					release: '7.3.0',
					mtime: 1519585935,
					db_size: 1250341,
				},
			},
			{
				text: 'GNU Fortran 6',
				data: {
					name: 'GNU Fortran',
					slug: 'gnu_fortran~6',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/fortran/',
					},
					version: '6',
					release: '6.4.0',
					mtime: 1503759905,
					db_size: 1133523,
				},
			},
			{
				text: 'GNU Fortran 5',
				data: {
					name: 'GNU Fortran',
					slug: 'gnu_fortran~5',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/fortran/',
					},
					version: '5',
					release: '5.4.0',
					mtime: 1469312374,
					db_size: 999032,
				},
			},
			{
				text: 'GNU Fortran 4',
				data: {
					name: 'GNU Fortran',
					slug: 'gnu_fortran~4',
					type: 'gnu',
					links: {
						home: 'https://gcc.gnu.org/fortran/',
					},
					version: '4',
					release: '4.9.3',
					mtime: 1460316067,
					db_size: 853323,
				},
			},
		],
	},
	{
		text: 'Go',
		data: {
			name: 'Go',
			slug: 'go',
			type: 'go',
			links: {
				home: 'https://golang.org/',
				code: 'https://go.googlesource.com/go',
			},
			release: '1.10.0',
			mtime: 1519572347,
			db_size: 3480319,
			isRoot: true,
		},
	},
	{
		text: 'Godot',
		data: {
			name: 'Godot',
			slug: 'godot~3.0',
			type: 'sphinx_simple',
			links: {
				home: 'https://godotengine.org/',
				code: 'https://github.com/godotengine/godot',
			},
			version: '3.0',
			release: '3.0',
			mtime: 1519572520,
			db_size: 3740908,
			isRoot: true,
		},
		children: [
			{
				text: 'Godot 3.0',
				data: {
					name: 'Godot',
					slug: 'godot~3.0',
					type: 'sphinx_simple',
					links: {
						home: 'https://godotengine.org/',
						code: 'https://github.com/godotengine/godot',
					},
					version: '3.0',
					release: '3.0',
					mtime: 1519572520,
					db_size: 3740908,
				},
			},
			{
				text: 'Godot 2.1',
				data: {
					name: 'Godot',
					slug: 'godot~2.1',
					type: 'sphinx_simple',
					links: {
						home: 'https://godotengine.org/',
						code: 'https://github.com/godotengine/godot',
					},
					version: '2.1',
					release: '2.1',
					mtime: 1500847393,
					db_size: 4249116,
				},
			},
		],
	},
	{
		text: 'Grunt',
		data: {
			name: 'Grunt',
			slug: 'grunt',
			type: 'grunt',
			release: '1.0.1',
			mtime: 1500740124,
			db_size: 183508,
			isRoot: true,
		},
	},
	{
		text: 'Haskell',
		data: {
			name: 'Haskell',
			slug: 'haskell~8',
			type: 'haskell',
			links: {
				home: 'https://www.haskell.org/',
			},
			version: '8',
			release: '8.2.1',
			mtime: 1503760719,
			db_size: 26228623,
			isRoot: true,
		},
		children: [
			{
				text: 'Haskell 8',
				data: {
					name: 'Haskell',
					slug: 'haskell~8',
					type: 'haskell',
					links: {
						home: 'https://www.haskell.org/',
					},
					version: '8',
					release: '8.2.1',
					mtime: 1503760719,
					db_size: 26228623,
				},
			},
			{
				text: 'Haskell 7',
				data: {
					name: 'Haskell',
					slug: 'haskell~7',
					type: 'haskell',
					links: {
						home: 'https://www.haskell.org/',
					},
					version: '7',
					release: '7.10.3',
					mtime: 1503760279,
					db_size: 6610017,
				},
			},
		],
	},
	{
		text: 'Haxe',
		data: {
			name: 'Haxe',
			slug: 'haxe',
			type: 'haxe',
			links: {
				home: 'https://haxe.org',
				code: 'https://github.com/HaxeFoundation/haxe',
			},
			version: '',
			release: '3.4.7',
			mtime: 1519586096,
			db_size: 1342836,
			isRoot: true,
		},
		children: [
			{
				text: 'Haxe',
				data: {
					name: 'Haxe',
					slug: 'haxe',
					type: 'haxe',
					links: {
						home: 'https://haxe.org',
						code: 'https://github.com/HaxeFoundation/haxe',
					},
					version: '',
					release: '3.4.7',
					mtime: 1519586096,
					db_size: 1342836,
				},
			},
			{
				text: 'Haxe C++',
				data: {
					name: 'Haxe',
					slug: 'haxe~cpp',
					type: 'haxe',
					version: 'C++',
					release: '3.4.7',
					mtime: 1519586098,
					db_size: 285939,
				},
			},
			{
				text: 'Haxe C#',
				data: {
					name: 'Haxe',
					slug: 'haxe~cs',
					type: 'haxe',
					version: 'C#',
					release: '3.4.7',
					mtime: 1519586118,
					db_size: 2287934,
				},
			},
			{
				text: 'Haxe Flash',
				data: {
					name: 'Haxe',
					slug: 'haxe~flash',
					type: 'haxe',
					version: 'Flash',
					release: '3.4.7',
					mtime: 1519586132,
					db_size: 1589211,
				},
			},
			{
				text: 'Haxe Java',
				data: {
					name: 'Haxe',
					slug: 'haxe~java',
					type: 'haxe',
					version: 'Java',
					release: '3.4.7',
					mtime: 1519586148,
					db_size: 1901861,
				},
			},
			{
				text: 'Haxe JavaScript',
				data: {
					name: 'Haxe',
					slug: 'haxe~javascript',
					type: 'haxe',
					version: 'JavaScript',
					release: '3.4.7',
					mtime: 1519586202,
					db_size: 3898907,
				},
			},
			{
				text: 'Haxe Neko',
				data: {
					name: 'Haxe',
					slug: 'haxe~neko',
					type: 'haxe',
					version: 'Neko',
					release: '3.4.7',
					mtime: 1519586204,
					db_size: 103569,
				},
			},
			{
				text: 'Haxe PHP',
				data: {
					name: 'Haxe',
					slug: 'haxe~php',
					type: 'haxe',
					version: 'PHP',
					release: '3.4.7',
					mtime: 1519586205,
					db_size: 73043,
				},
			},
			{
				text: 'Haxe Python',
				data: {
					name: 'Haxe',
					slug: 'haxe~python',
					type: 'haxe',
					version: 'Python',
					release: '3.4.7',
					mtime: 1519586210,
					db_size: 549685,
				},
			},
		],
	},
	{
		text: 'Homebrew',
		data: {
			name: 'Homebrew',
			slug: 'homebrew',
			type: 'simple',
			links: {
				home: 'https://brew.sh',
				code: 'https://github.com/Homebrew/brew',
			},
			release: '1.4.2',
			mtime: 1515367956,
			db_size: 684702,
			isRoot: true,
		},
	},
	{
		text: 'HTML',
		data: {
			name: 'HTML',
			slug: 'html',
			type: 'mdn',
			mtime: 1521397030,
			db_size: 3812899,
			isRoot: true,
		},
	},
	{
		text: 'HTTP',
		data: {
			name: 'HTTP',
			slug: 'http',
			type: 'mdn',
			mtime: 1521397177,
			db_size: 4390235,
			isRoot: true,
		},
	},
	{
		text: 'Immutable.js',
		data: {
			name: 'Immutable.js',
			slug: 'immutable',
			type: 'immutable',
			links: {
				home: 'https://facebook.github.io/immutable-js/',
				code: 'https://github.com/facebook/immutable-js',
			},
			release: '3.8.1',
			mtime: 1479652557,
			db_size: 742765,
			isRoot: true,
		},
	},
	{
		text: 'InfluxData',
		data: {
			name: 'InfluxData',
			slug: 'influxdata',
			type: 'influxdata',
			links: {
				home: 'https://www.influxdata.com/',
				code: 'https://github.com/influxdata/influxdb',
			},
			release: '1.3',
			mtime: 1501448812,
			db_size: 3582825,
			isRoot: true,
		},
	},
	{
		text: 'Jasmine',
		data: {
			name: 'Jasmine',
			slug: 'jasmine',
			type: 'jasmine',
			links: {
				home: 'https://jasmine.github.io/',
				code: 'https://github.com/jasmine/jasmine',
			},
			release: '3.0.0',
			mtime: 1519572575,
			db_size: 86239,
			isRoot: true,
		},
	},
	{
		text: 'JavaScript',
		data: {
			name: 'JavaScript',
			slug: 'javascript',
			type: 'mdn',
			mtime: 1521399307,
			db_size: 6130002,
			isRoot: true,
		},
	},
	{
		text: 'Jekyll',
		data: {
			name: 'Jekyll',
			slug: 'jekyll',
			type: 'jekyll',
			links: {
				home: 'https://jekyllrb.com/',
				code: 'https://github.com/jekyll/jekyll',
			},
			release: '3.7.2',
			mtime: 1517761163,
			db_size: 334606,
			isRoot: true,
		},
	},
	{
		text: 'Jest',
		data: {
			name: 'Jest',
			slug: 'jest',
			type: 'jest',
			links: {
				home: 'https://facebook.github.io/jest/',
				code: 'https://github.com/facebook/jest',
			},
			release: '22.3.0',
			mtime: 1519572598,
			db_size: 390775,
			isRoot: true,
		},
	},
	{
		text: 'jQuery',
		data: {
			name: 'jQuery',
			slug: 'jquery',
			type: 'jquery',
			release: 'up to 3.3.1',
			mtime: 1517183393,
			db_size: 2680445,
			isRoot: true,
		},
	},
	{
		text: 'jQuery Mobile',
		data: {
			name: 'jQuery Mobile',
			slug: 'jquerymobile',
			type: 'jquery',
			release: '1.4.5',
			mtime: 1500821575,
			db_size: 1120776,
			isRoot: true,
		},
	},
	{
		text: 'jQuery UI',
		data: {
			name: 'jQuery UI',
			slug: 'jqueryui',
			type: 'jquery',
			release: '1.12.1',
			mtime: 1500821446,
			db_size: 1099745,
			isRoot: true,
		},
	},
	{
		text: 'JSDoc',
		data: {
			name: 'JSDoc',
			slug: 'jsdoc',
			type: 'simple',
			links: {
				home: 'http://usejsdoc.org/',
				code: 'https://github.com/jsdoc3/jsdoc',
			},
			release: '3.5.5',
			mtime: 1517758919,
			db_size: 283935,
			isRoot: true,
		},
	},
	{
		text: 'Julia',
		data: {
			name: 'Julia',
			slug: 'julia~0.6',
			type: 'julia',
			links: {
				home: 'https://julialang.org/',
				code: 'https://github.com/JuliaLang/julia',
			},
			version: '0.6',
			release: '0.6.2',
			mtime: 1515368111,
			db_size: 2721254,
			isRoot: true,
		},
		children: [
			{
				text: 'Julia 0.6',
				data: {
					name: 'Julia',
					slug: 'julia~0.6',
					type: 'julia',
					links: {
						home: 'https://julialang.org/',
						code: 'https://github.com/JuliaLang/julia',
					},
					version: '0.6',
					release: '0.6.2',
					mtime: 1515368111,
					db_size: 2721254,
				},
			},
			{
				text: 'Julia 0.5',
				data: {
					name: 'Julia',
					slug: 'julia~0.5',
					type: 'sphinx_simple',
					links: {
						home: 'https://julialang.org/',
						code: 'https://github.com/JuliaLang/julia',
					},
					version: '0.5',
					release: '0.5.2',
					mtime: 1498401014,
					db_size: 2184173,
				},
			},
		],
	},
	{
		text: 'Knockout.js',
		data: {
			name: 'Knockout.js',
			slug: 'knockout',
			type: 'knockout',
			release: '3.4.2',
			mtime: 1489346587,
			db_size: 417406,
			isRoot: true,
		},
	},
	{
		text: 'Kotlin',
		data: {
			name: 'Kotlin',
			slug: 'kotlin',
			type: 'kotlin',
			links: {
				home: 'https://kotlinlang.org/',
				code: 'https://github.com/JetBrains/kotlin',
			},
			release: '1.2.21',
			mtime: 1519572966,
			db_size: 11668563,
			isRoot: true,
		},
	},
	{
		text: 'Laravel',
		data: {
			name: 'Laravel',
			slug: 'laravel~5.6',
			type: 'laravel',
			links: {
				home: 'https://laravel.com/',
				code: 'https://github.com/laravel/laravel',
			},
			version: '5.6',
			release: '5.6.12',
			mtime: 1521387069,
			db_size: 19191967,
			isRoot: true,
		},
		children: [
			{
				text: 'Laravel 5.6',
				data: {
					name: 'Laravel',
					slug: 'laravel~5.6',
					type: 'laravel',
					links: {
						home: 'https://laravel.com/',
						code: 'https://github.com/laravel/laravel',
					},
					version: '5.6',
					release: '5.6.12',
					mtime: 1521387069,
					db_size: 19191967,
				},
			},
			{
				text: 'Laravel 5.5',
				data: {
					name: 'Laravel',
					slug: 'laravel~5.5',
					type: 'laravel',
					links: {
						home: 'https://laravel.com/',
						code: 'https://github.com/laravel/laravel',
					},
					version: '5.5',
					release: '5.5.28',
					mtime: 1515368259,
					db_size: 17701623,
				},
			},
			{
				text: 'Laravel 5.4',
				data: {
					name: 'Laravel',
					slug: 'laravel~5.4',
					type: 'laravel',
					links: {
						home: 'https://laravel.com/',
						code: 'https://github.com/laravel/laravel',
					},
					version: '5.4',
					release: '5.4.30',
					mtime: 1505054925,
					db_size: 16448730,
				},
			},
			{
				text: 'Laravel 5.3',
				data: {
					name: 'Laravel',
					slug: 'laravel~5.3',
					type: 'laravel',
					links: {
						home: 'https://laravel.com/',
						code: 'https://github.com/laravel/laravel',
					},
					version: '5.3',
					release: '5.3.30',
					mtime: 1505055249,
					db_size: 14614370,
				},
			},
			{
				text: 'Laravel 5.2',
				data: {
					name: 'Laravel',
					slug: 'laravel~5.2',
					type: 'laravel',
					links: {
						home: 'https://laravel.com/',
						code: 'https://github.com/laravel/laravel',
					},
					version: '5.2',
					release: '5.2.31',
					mtime: 1505055328,
					db_size: 12870495,
				},
			},
			{
				text: 'Laravel 5.1',
				data: {
					name: 'Laravel',
					slug: 'laravel~5.1',
					type: 'laravel',
					links: {
						home: 'https://laravel.com/',
						code: 'https://github.com/laravel/laravel',
					},
					version: '5.1',
					release: '5.1.33',
					mtime: 1505055406,
					db_size: 11737667,
				},
			},
			{
				text: 'Laravel 4.2',
				data: {
					name: 'Laravel',
					slug: 'laravel~4.2',
					type: 'laravel',
					links: {
						home: 'https://laravel.com/',
						code: 'https://github.com/laravel/laravel',
					},
					version: '4.2',
					release: '4.2.11',
					mtime: 1505055134,
					db_size: 7711773,
				},
			},
		],
	},
	{
		text: 'Less',
		data: {
			name: 'Less',
			slug: 'less',
			type: 'less',
			links: {
				home: 'http://lesscss.org/',
				code: 'https://github.com/less/less.js',
			},
			release: '2.7.2',
			mtime: 1495470772,
			db_size: 150274,
			isRoot: true,
		},
	},
	{
		text: 'Liquid',
		data: {
			name: 'Liquid',
			slug: 'liquid',
			type: 'liquid',
			links: {
				home: 'https://shopify.github.io/liquid/',
				code: 'https://github.com/Shopify/liquid',
			},
			release: '4.0.0',
			mtime: 1498406903,
			db_size: 74772,
			isRoot: true,
		},
	},
	{
		text: 'lodash',
		data: {
			name: 'lodash',
			slug: 'lodash~4',
			type: 'lodash',
			links: {
				home: 'https://lodash.com/',
				code: 'https://github.com/lodash/lodash/',
			},
			version: '4',
			release: '4.17.5',
			mtime: 1521386851,
			db_size: 336272,
			isRoot: true,
		},
		children: [
			{
				text: 'lodash 4',
				data: {
					name: 'lodash',
					slug: 'lodash~4',
					type: 'lodash',
					links: {
						home: 'https://lodash.com/',
						code: 'https://github.com/lodash/lodash/',
					},
					version: '4',
					release: '4.17.5',
					mtime: 1521386851,
					db_size: 336272,
				},
			},
			{
				text: 'lodash 3',
				data: {
					name: 'lodash',
					slug: 'lodash~3',
					type: 'lodash',
					links: {
						home: 'https://lodash.com/',
						code: 'https://github.com/lodash/lodash/',
					},
					version: '3',
					release: '3.10.1',
					mtime: 1475414357,
					db_size: 264546,
				},
			},
			{
				text: 'lodash 2',
				data: {
					name: 'lodash',
					slug: 'lodash~2',
					type: 'lodash',
					links: {
						home: 'https://lodash.com/',
						code: 'https://github.com/lodash/lodash/',
					},
					version: '2',
					release: '2.4.2',
					mtime: 1475414359,
					db_size: 172643,
				},
			},
		],
	},
	{
		text: 'Lua',
		data: {
			name: 'Lua',
			slug: 'lua~5.3',
			type: 'lua',
			version: '5.3',
			release: '5.3.4',
			mtime: 1500739922,
			db_size: 325966,
			isRoot: true,
		},
		children: [
			{
				text: 'Lua 5.3',
				data: {
					name: 'Lua',
					slug: 'lua~5.3',
					type: 'lua',
					version: '5.3',
					release: '5.3.4',
					mtime: 1500739922,
					db_size: 325966,
				},
			},
			{
				text: 'Lua 5.2',
				data: {
					name: 'Lua',
					slug: 'lua~5.2',
					type: 'lua',
					version: '5.2',
					release: '5.2.4',
					mtime: 1500739926,
					db_size: 304632,
				},
			},
			{
				text: 'Lua 5.1',
				data: {
					name: 'Lua',
					slug: 'lua~5.1',
					type: 'lua',
					version: '5.1',
					release: '5.1.5',
					mtime: 1500739929,
					db_size: 253404,
				},
			},
		],
	},
	{
		text: 'LÖVE',
		data: {
			name: 'LÖVE',
			slug: 'love',
			type: 'love',
			links: {
				home: 'https://love2d.org/',
				code: 'https://bitbucket.org/rude/love',
			},
			release: '0.10.2',
			mtime: 1480270799,
			db_size: 2655816,
			isRoot: true,
		},
	},
	{
		text: 'Marionette.js',
		data: {
			name: 'Marionette.js',
			slug: 'marionette~3',
			type: 'marionette',
			links: {
				home: 'https://marionettejs.com/',
				code: 'https://github.com/marionettejs/backbone.marionette',
			},
			version: '3',
			release: '3.5.1',
			mtime: 1510332195,
			db_size: 503494,
			isRoot: true,
		},
		children: [
			{
				text: 'Marionette.js 3',
				data: {
					name: 'Marionette.js',
					slug: 'marionette~3',
					type: 'marionette',
					links: {
						home: 'https://marionettejs.com/',
						code: 'https://github.com/marionettejs/backbone.marionette',
					},
					version: '3',
					release: '3.5.1',
					mtime: 1510332195,
					db_size: 503494,
				},
			},
			{
				text: 'Marionette.js 2',
				data: {
					name: 'Marionette.js',
					slug: 'marionette~2',
					type: 'marionette',
					links: {
						home: 'https://marionettejs.com/',
						code: 'https://github.com/marionettejs/backbone.marionette',
					},
					version: '2',
					release: '2.4.7',
					mtime: 1479678843,
					db_size: 319692,
				},
			},
		],
	},
	{
		text: 'Markdown',
		data: {
			name: 'Markdown',
			slug: 'markdown',
			type: 'markdown',
			mtime: 1426424874,
			db_size: 31338,
			isRoot: true,
		},
	},
	{
		text: 'Matplotlib',
		data: {
			name: 'Matplotlib',
			slug: 'matplotlib~2.1',
			type: 'sphinx',
			links: {
				home: 'http://matplotlib.org/',
				code: 'https://github.com/matplotlib/matplotlib',
			},
			version: '2.1',
			release: '2.1.0',
			mtime: 1509301001,
			db_size: 32934732,
			isRoot: true,
		},
		children: [
			{
				text: 'Matplotlib 2.1',
				data: {
					name: 'Matplotlib',
					slug: 'matplotlib~2.1',
					type: 'sphinx',
					links: {
						home: 'http://matplotlib.org/',
						code: 'https://github.com/matplotlib/matplotlib',
					},
					version: '2.1',
					release: '2.1.0',
					mtime: 1509301001,
					db_size: 32934732,
				},
			},
			{
				text: 'Matplotlib 2.0',
				data: {
					name: 'Matplotlib',
					slug: 'matplotlib~2.0',
					type: 'sphinx',
					links: {
						home: 'http://matplotlib.org/',
						code: 'https://github.com/matplotlib/matplotlib',
					},
					version: '2.0',
					release: '2.0.2',
					mtime: 1498401455,
					db_size: 5137554,
				},
			},
			{
				text: 'Matplotlib 1.5',
				data: {
					name: 'Matplotlib',
					slug: 'matplotlib~1.5',
					type: 'sphinx',
					links: {
						home: 'http://matplotlib.org/',
						code: 'https://github.com/matplotlib/matplotlib',
					},
					version: '1.5',
					release: '1.5.3',
					mtime: 1483389014,
					db_size: 3803905,
				},
			},
		],
	},
	{
		text: 'Meteor',
		data: {
			name: 'Meteor',
			slug: 'meteor~1.5',
			type: 'meteor',
			links: {
				home: 'https://www.meteor.com/',
				code: 'https://github.com/meteor/meteor/',
			},
			version: '1.5',
			release: '1.5.2',
			mtime: 1509301490,
			db_size: 2121693,
			isRoot: true,
		},
		children: [
			{
				text: 'Meteor 1.5',
				data: {
					name: 'Meteor',
					slug: 'meteor~1.5',
					type: 'meteor',
					links: {
						home: 'https://www.meteor.com/',
						code: 'https://github.com/meteor/meteor/',
					},
					version: '1.5',
					release: '1.5.2',
					mtime: 1509301490,
					db_size: 2121693,
				},
			},
			{
				text: 'Meteor 1.4',
				data: {
					name: 'Meteor',
					slug: 'meteor~1.4',
					type: 'meteor',
					links: {
						home: 'https://www.meteor.com/',
						code: 'https://github.com/meteor/meteor/',
					},
					version: '1.4',
					release: '1.4.4',
					mtime: 1501449312,
					db_size: 2509309,
				},
			},
			{
				text: 'Meteor 1.3',
				data: {
					name: 'Meteor',
					slug: 'meteor~1.3',
					type: 'meteor',
					links: {
						home: 'https://www.meteor.com/',
						code: 'https://github.com/meteor/meteor/',
					},
					version: '1.3',
					release: '1.3.5',
					mtime: 1501449342,
					db_size: 2442819,
				},
			},
		],
	},
	{
		text: 'Mocha',
		data: {
			name: 'Mocha',
			slug: 'mocha',
			type: 'mocha',
			links: {
				home: 'https://mochajs.org/',
				code: 'https://github.com/mochajs/mocha',
			},
			release: '5.0.1',
			mtime: 1519573130,
			db_size: 1021241,
			isRoot: true,
		},
	},
	{
		text: 'Modernizr',
		data: {
			name: 'Modernizr',
			slug: 'modernizr',
			type: 'modernizr',
			release: '3.5.0',
			mtime: 1492958610,
			db_size: 78016,
			isRoot: true,
		},
	},
	{
		text: 'Moment.js',
		data: {
			name: 'Moment.js',
			slug: 'moment',
			type: 'moment',
			links: {
				home: 'http://momentjs.com/',
				code: 'https://github.com/moment/moment/',
			},
			release: '2.21.0',
			mtime: 1521386586,
			db_size: 294905,
			isRoot: true,
		},
	},
	{
		text: 'Mongoose',
		data: {
			name: 'Mongoose',
			slug: 'mongoose',
			type: 'mongoose',
			links: {
				home: 'http://mongoosejs.com/',
				code: 'https://github.com/Automattic/mongoose',
			},
			release: '4.13.1',
			mtime: 1510332286,
			db_size: 703709,
			isRoot: true,
		},
	},
	{
		text: 'nginx',
		data: {
			name: 'nginx',
			slug: 'nginx',
			type: 'nginx',
			links: {
				home: 'https://nginx.org/',
				code: 'http://hg.nginx.org/nginx',
			},
			release: '1.13.10',
			mtime: 1521915393,
			db_size: 1377191,
			isRoot: true,
		},
	},
	{
		text: 'nginx / Lua Module',
		data: {
			name: 'nginx / Lua Module',
			slug: 'nginx_lua_module',
			type: 'github',
			release: '0.10.11',
			mtime: 1519573350,
			db_size: 427302,
			isRoot: true,
		},
	},
	{
		text: 'Nim',
		data: {
			name: 'Nim',
			slug: 'nim',
			type: 'nim',
			links: {
				home: 'https://nim-lang.org/',
				code: 'https://github.com/nim-lang/Nim',
			},
			release: '0.18.0',
			mtime: 1521386382,
			db_size: 2759321,
			isRoot: true,
		},
	},
	{
		text: 'Node.js',
		data: {
			name: 'Node.js',
			slug: 'node',
			type: 'node',
			links: {
				home: 'https://nodejs.org/',
				code: 'https://github.com/nodejs/node',
			},
			version: '',
			release: '9.8.0',
			mtime: 1521387284,
			db_size: 2286687,
			isRoot: true,
		},
		children: [
			{
				text: 'Node.js',
				data: {
					name: 'Node.js',
					slug: 'node',
					type: 'node',
					links: {
						home: 'https://nodejs.org/',
						code: 'https://github.com/nodejs/node',
					},
					version: '',
					release: '9.8.0',
					mtime: 1521387284,
					db_size: 2286687,
				},
			},
			{
				text: 'Node.js 8 LTS',
				data: {
					name: 'Node.js',
					slug: 'node~8_lts',
					type: 'node',
					links: {
						home: 'https://nodejs.org/',
						code: 'https://github.com/nodejs/node',
					},
					version: '8 LTS',
					release: '8.10.0',
					mtime: 1521387289,
					db_size: 2145881,
				},
			},
			{
				text: 'Node.js 6 LTS',
				data: {
					name: 'Node.js',
					slug: 'node~6_lts',
					type: 'node',
					links: {
						home: 'https://nodejs.org/',
						code: 'https://github.com/nodejs/node',
					},
					version: '6 LTS',
					release: '6.13.1',
					mtime: 1521387292,
					db_size: 1437522,
				},
			},
			{
				text: 'Node.js 4 LTS',
				data: {
					name: 'Node.js',
					slug: 'node~4_lts',
					type: 'node',
					links: {
						home: 'https://nodejs.org/',
						code: 'https://github.com/nodejs/node',
					},
					version: '4 LTS',
					release: '4.8.7',
					mtime: 1521387294,
					db_size: 982448,
				},
			},
		],
	},
	{
		text: 'Nokogiri',
		data: {
			name: 'Nokogiri',
			slug: 'nokogiri',
			type: 'rdoc',
			release: '1.8.1',
			mtime: 1507477019,
			db_size: 500307,
			isRoot: true,
		},
	},
	{
		text: 'npm',
		data: {
			name: 'npm',
			slug: 'npm',
			type: 'npm',
			links: {
				home: 'https://www.npmjs.com/',
				code: 'https://github.com/npm/npm',
			},
			release: '5.8.0',
			mtime: 1521915629,
			db_size: 1567095,
			isRoot: true,
		},
	},
	{
		text: 'NumPy',
		data: {
			name: 'NumPy',
			slug: 'numpy~1.13',
			type: 'sphinx',
			links: {
				home: 'http://www.numpy.org/',
				code: 'https://github.com/numpy/numpy',
			},
			version: '1.13',
			release: '1.13.0',
			mtime: 1498401762,
			db_size: 6106757,
			isRoot: true,
		},
		children: [
			{
				text: 'NumPy 1.13',
				data: {
					name: 'NumPy',
					slug: 'numpy~1.13',
					type: 'sphinx',
					links: {
						home: 'http://www.numpy.org/',
						code: 'https://github.com/numpy/numpy',
					},
					version: '1.13',
					release: '1.13.0',
					mtime: 1498401762,
					db_size: 6106757,
				},
			},
			{
				text: 'NumPy 1.12',
				data: {
					name: 'NumPy',
					slug: 'numpy~1.12',
					type: 'sphinx',
					links: {
						home: 'http://www.numpy.org/',
						code: 'https://github.com/numpy/numpy',
					},
					version: '1.12',
					release: '1.12.0',
					mtime: 1498401838,
					db_size: 5936289,
				},
			},
			{
				text: 'NumPy 1.11',
				data: {
					name: 'NumPy',
					slug: 'numpy~1.11',
					type: 'sphinx',
					links: {
						home: 'http://www.numpy.org/',
						code: 'https://github.com/numpy/numpy',
					},
					version: '1.11',
					release: '1.11.0',
					mtime: 1467583174,
					db_size: 5869485,
				},
			},
			{
				text: 'NumPy 1.10',
				data: {
					name: 'NumPy',
					slug: 'numpy~1.10',
					type: 'sphinx',
					links: {
						home: 'http://www.numpy.org/',
						code: 'https://github.com/numpy/numpy',
					},
					version: '1.10',
					release: '1.10.4',
					mtime: 1467583024,
					db_size: 5821391,
				},
			},
		],
	},
	{
		text: 'OpenJDK',
		data: {
			name: 'OpenJDK',
			slug: 'openjdk~8',
			type: 'openjdk',
			version: '8',
			release: '8',
			mtime: 1493584121,
			db_size: 24834497,
			isRoot: true,
		},
		children: [
			{
				text: 'OpenJDK 8',
				data: {
					name: 'OpenJDK',
					slug: 'openjdk~8',
					type: 'openjdk',
					version: '8',
					release: '8',
					mtime: 1493584121,
					db_size: 24834497,
				},
			},
			{
				text: 'OpenJDK 8 GUI',
				data: {
					name: 'OpenJDK',
					slug: 'openjdk~8_gui',
					type: 'openjdk',
					version: '8 GUI',
					release: '8',
					mtime: 1493584418,
					db_size: 16427435,
				},
			},
			{
				text: 'OpenJDK 8 Web',
				data: {
					name: 'OpenJDK',
					slug: 'openjdk~8_web',
					type: 'openjdk',
					version: '8 Web',
					release: '8',
					mtime: 1493584241,
					db_size: 9963945,
				},
			},
		],
	},
	{
		text: 'OpenTSDB',
		data: {
			name: 'OpenTSDB',
			slug: 'opentsdb',
			type: 'sphinx_simple',
			links: {
				home: 'http://opentsdb.net/',
				code: 'https://github.com/OpenTSDB/opentsdb',
			},
			release: '2.3.0',
			mtime: 1483389649,
			db_size: 889359,
			isRoot: true,
		},
	},
	{
		text: 'Padrino',
		data: {
			name: 'Padrino',
			slug: 'padrino',
			type: 'rubydoc',
			links: {
				home: 'http://padrinorb.com/',
				code: 'https://github.com/padrino/padrino-framework',
			},
			release: '0.14.1',
			mtime: 1509291624,
			db_size: 868484,
			isRoot: true,
		},
	},
	{
		text: 'pandas',
		data: {
			name: 'pandas',
			slug: 'pandas~0.22',
			type: 'sphinx',
			links: {
				home: 'http://pandas.pydata.org/',
				code: 'https://github.com/pydata/pandas',
			},
			version: '0.22',
			release: '0.22.0',
			mtime: 1515368658,
			db_size: 4723621,
			isRoot: true,
		},
		children: [
			{
				text: 'pandas 0.22',
				data: {
					name: 'pandas',
					slug: 'pandas~0.22',
					type: 'sphinx',
					links: {
						home: 'http://pandas.pydata.org/',
						code: 'https://github.com/pydata/pandas',
					},
					version: '0.22',
					release: '0.22.0',
					mtime: 1515368658,
					db_size: 4723621,
				},
			},
			{
				text: 'pandas 0.21',
				data: {
					name: 'pandas',
					slug: 'pandas~0.21',
					type: 'sphinx',
					links: {
						home: 'http://pandas.pydata.org/',
						code: 'https://github.com/pydata/pandas',
					},
					version: '0.21',
					release: '0.21.0',
					mtime: 1509302634,
					db_size: 4704212,
				},
			},
			{
				text: 'pandas 0.20',
				data: {
					name: 'pandas',
					slug: 'pandas~0.20',
					type: 'sphinx',
					links: {
						home: 'http://pandas.pydata.org/',
						code: 'https://github.com/pydata/pandas',
					},
					version: '0.20',
					release: '0.20.3',
					mtime: 1509302472,
					db_size: 4289994,
				},
			},
			{
				text: 'pandas 0.19',
				data: {
					name: 'pandas',
					slug: 'pandas~0.19',
					type: 'sphinx',
					links: {
						home: 'http://pandas.pydata.org/',
						code: 'https://github.com/pydata/pandas',
					},
					version: '0.19',
					release: '0.19.2',
					mtime: 1498402457,
					db_size: 5574756,
				},
			},
			{
				text: 'pandas 0.18',
				data: {
					name: 'pandas',
					slug: 'pandas~0.18',
					type: 'sphinx',
					links: {
						home: 'http://pandas.pydata.org/',
						code: 'https://github.com/pydata/pandas',
					},
					version: '0.18',
					release: '0.18.1',
					mtime: 1476112392,
					db_size: 5310831,
				},
			},
		],
	},
	{
		text: 'Perl',
		data: {
			name: 'Perl',
			slug: 'perl~5.26',
			type: 'perl',
			links: {
				home: 'https://www.perl.org/',
			},
			version: '5.26',
			release: '5.26.0',
			mtime: 1500742523,
			db_size: 14046450,
			isRoot: true,
		},
		children: [
			{
				text: 'Perl 5.26',
				data: {
					name: 'Perl',
					slug: 'perl~5.26',
					type: 'perl',
					links: {
						home: 'https://www.perl.org/',
					},
					version: '5.26',
					release: '5.26.0',
					mtime: 1500742523,
					db_size: 14046450,
				},
			},
			{
				text: 'Perl 5.24',
				data: {
					name: 'Perl',
					slug: 'perl~5.24',
					type: 'perl',
					links: {
						home: 'https://www.perl.org/',
					},
					version: '5.24',
					release: '5.24.0',
					mtime: 1500742737,
					db_size: 14166764,
				},
			},
			{
				text: 'Perl 5.22',
				data: {
					name: 'Perl',
					slug: 'perl~5.22',
					type: 'perl',
					links: {
						home: 'https://www.perl.org/',
					},
					version: '5.22',
					release: '5.22.0',
					mtime: 1500742852,
					db_size: 14046450,
				},
			},
			{
				text: 'Perl 5.20',
				data: {
					name: 'Perl',
					slug: 'perl~5.20',
					type: 'perl',
					links: {
						home: 'https://www.perl.org/',
					},
					version: '5.20',
					release: '5.20.2',
					mtime: 1500742940,
					db_size: 14101118,
				},
			},
		],
	},
	{
		text: 'Phalcon',
		data: {
			name: 'Phalcon',
			slug: 'phalcon~3',
			type: 'phalcon',
			links: {
				home: 'https://phalconphp.com/',
				code: 'https://github.com/phalcon/cphalcon/',
			},
			version: '3',
			release: '3.1.1',
			mtime: 1495471186,
			db_size: 3296452,
			isRoot: true,
		},
		children: [
			{
				text: 'Phalcon 3',
				data: {
					name: 'Phalcon',
					slug: 'phalcon~3',
					type: 'phalcon',
					links: {
						home: 'https://phalconphp.com/',
						code: 'https://github.com/phalcon/cphalcon/',
					},
					version: '3',
					release: '3.1.1',
					mtime: 1495471186,
					db_size: 3296452,
				},
			},
			{
				text: 'Phalcon 2',
				data: {
					name: 'Phalcon',
					slug: 'phalcon~2',
					type: 'phalcon',
					links: {
						home: 'https://phalconphp.com/',
						code: 'https://github.com/phalcon/cphalcon/',
					},
					version: '2',
					release: '2.0.13',
					mtime: 1475334683,
					db_size: 2714996,
				},
			},
		],
	},
	{
		text: 'Phaser',
		data: {
			name: 'Phaser',
			slug: 'phaser',
			type: 'phaser',
			links: {
				home: 'http://phaser.io/',
				code: 'https://github.com/photonstorm/phaser',
			},
			release: '2.6.2',
			mtime: 1472404795,
			db_size: 6877092,
			isRoot: true,
		},
	},
	{
		text: 'Phoenix',
		data: {
			name: 'Phoenix',
			slug: 'phoenix',
			type: 'elixir',
			links: {
				home: 'http://www.phoenixframework.org',
				code: 'https://github.com/phoenixframework/phoenix',
			},
			release: '1.3.0',
			mtime: 1503762394,
			db_size: 1654985,
			isRoot: true,
		},
	},
	{
		text: 'PHP',
		data: {
			name: 'PHP',
			slug: 'php',
			type: 'php',
			links: {
				home: 'https://secure.php.net/',
				code: 'https://git.php.net/?p=php-src.git;a=summary',
			},
			release: '7.2.2',
			mtime: 1519586580,
			db_size: 24079784,
			isRoot: true,
		},
	},
	{
		text: 'PHPUnit',
		data: {
			name: 'PHPUnit',
			slug: 'phpunit~6',
			type: 'phpunit',
			links: {
				home: 'https://phpunit.de/',
				code: 'https://github.com/sebastianbergmann/phpunit',
			},
			version: '6',
			release: '6.5',
			mtime: 1515368674,
			db_size: 394690,
			isRoot: true,
		},
		children: [
			{
				text: 'PHPUnit 6',
				data: {
					name: 'PHPUnit',
					slug: 'phpunit~6',
					type: 'phpunit',
					links: {
						home: 'https://phpunit.de/',
						code: 'https://github.com/sebastianbergmann/phpunit',
					},
					version: '6',
					release: '6.5',
					mtime: 1515368674,
					db_size: 394690,
				},
			},
			{
				text: 'PHPUnit 5',
				data: {
					name: 'PHPUnit',
					slug: 'phpunit~5',
					type: 'phpunit',
					links: {
						home: 'https://phpunit.de/',
						code: 'https://github.com/sebastianbergmann/phpunit',
					},
					version: '5',
					release: '5.7',
					mtime: 1483389936,
					db_size: 393964,
				},
			},
			{
				text: 'PHPUnit 4',
				data: {
					name: 'PHPUnit',
					slug: 'phpunit~4',
					type: 'phpunit',
					links: {
						home: 'https://phpunit.de/',
						code: 'https://github.com/sebastianbergmann/phpunit',
					},
					version: '4',
					release: '4.8',
					mtime: 1469313483,
					db_size: 413036,
				},
			},
		],
	},
	{
		text: 'PostgreSQL',
		data: {
			name: 'PostgreSQL',
			slug: 'postgresql~10',
			type: 'postgres',
			links: {
				home: 'https://www.postgresql.org/',
				code: 'https://git.postgresql.org/gitweb/?p=postgresql.git',
			},
			version: '10',
			release: '10.2',
			mtime: 1519573707,
			db_size: 6484308,
			isRoot: true,
		},
		children: [
			{
				text: 'PostgreSQL 10',
				data: {
					name: 'PostgreSQL',
					slug: 'postgresql~10',
					type: 'postgres',
					links: {
						home: 'https://www.postgresql.org/',
						code: 'https://git.postgresql.org/gitweb/?p=postgresql.git',
					},
					version: '10',
					release: '10.2',
					mtime: 1519573707,
					db_size: 6484308,
				},
			},
			{
				text: 'PostgreSQL 9.6',
				data: {
					name: 'PostgreSQL',
					slug: 'postgresql~9.6',
					type: 'postgres',
					links: {
						home: 'https://www.postgresql.org/',
						code: 'https://git.postgresql.org/gitweb/?p=postgresql.git',
					},
					version: '9.6',
					release: '9.6.6',
					mtime: 1510331640,
					db_size: 5816975,
				},
			},
			{
				text: 'PostgreSQL 9.5',
				data: {
					name: 'PostgreSQL',
					slug: 'postgresql~9.5',
					type: 'postgres',
					links: {
						home: 'https://www.postgresql.org/',
						code: 'https://git.postgresql.org/gitweb/?p=postgresql.git',
					},
					version: '9.5',
					release: '9.5.10',
					mtime: 1510331714,
					db_size: 5569465,
				},
			},
			{
				text: 'PostgreSQL 9.4',
				data: {
					name: 'PostgreSQL',
					slug: 'postgresql~9.4',
					type: 'postgres',
					links: {
						home: 'https://www.postgresql.org/',
						code: 'https://git.postgresql.org/gitweb/?p=postgresql.git',
					},
					version: '9.4',
					release: '9.4.15',
					mtime: 1510331828,
					db_size: 5212360,
				},
			},
		],
	},
	{
		text: 'Pug',
		data: {
			name: 'Pug',
			slug: 'pug',
			type: 'pug',
			links: {
				home: 'https://pugjs.org/',
				code: 'https://github.com/pugjs/pug',
			},
			release: '2.0.3',
			mtime: 1521915454,
			db_size: 78298,
			isRoot: true,
		},
	},
	{
		text: 'Python',
		data: {
			name: 'Python',
			slug: 'python~3.6',
			type: 'sphinx',
			links: {
				home: 'https://www.python.org/',
				code: 'https://github.com/python/cpython',
			},
			version: '3.6',
			release: '3.6.4',
			mtime: 1515368831,
			db_size: 8006465,
			isRoot: true,
		},
		children: [
			{
				text: 'Python 3.6',
				data: {
					name: 'Python',
					slug: 'python~3.6',
					type: 'sphinx',
					links: {
						home: 'https://www.python.org/',
						code: 'https://github.com/python/cpython',
					},
					version: '3.6',
					release: '3.6.4',
					mtime: 1515368831,
					db_size: 8006465,
				},
			},
			{
				text: 'Python 3.5',
				data: {
					name: 'Python',
					slug: 'python~3.5',
					type: 'sphinx',
					links: {
						home: 'https://www.python.org/',
						code: 'https://github.com/python/cpython',
					},
					version: '3.5',
					release: '3.5.3',
					mtime: 1490460934,
					db_size: 7678626,
				},
			},
			{
				text: 'Python 2.7',
				data: {
					name: 'Python',
					slug: 'python~2.7',
					type: 'sphinx',
					links: {
						home: 'https://www.python.org/',
						code: 'https://github.com/python/cpython',
					},
					version: '2.7',
					release: '2.7.13',
					mtime: 1490461005,
					db_size: 6466541,
				},
			},
		],
	},
	{
		text: 'Q',
		data: {
			name: 'Q',
			slug: 'q',
			type: 'github',
			links: {
				home: 'http://documentup.com/kriskowal/q/',
				code: 'https://github.com/kriskowal/q',
			},
			release: '1.5.1',
			mtime: 1509302829,
			db_size: 29687,
			isRoot: true,
		},
	},
	{
		text: 'Ramda',
		data: {
			name: 'Ramda',
			slug: 'ramda',
			type: 'ramda',
			links: {
				home: 'http://ramdajs.com/',
				code: 'https://github.com/ramda/ramda/',
			},
			release: '0.25.0',
			mtime: 1509302864,
			db_size: 271964,
			isRoot: true,
		},
	},
	{
		text: 'React',
		data: {
			name: 'React',
			slug: 'react',
			type: 'simple',
			links: {
				home: 'https://reactjs.org/',
				code: 'https://github.com/facebook/react',
			},
			release: '16.2.0',
			mtime: 1515369055,
			db_size: 716063,
			isRoot: true,
		},
	},
	{
		text: 'ReactNative',
		data: {
			name: 'ReactNative',
			slug: 'react_native',
			type: 'react_native',
			links: {
				home: 'https://facebook.github.io/react-native/',
				code: 'https://github.com/facebook/react-native',
			},
			release: '0.49',
			mtime: 1507560654,
			db_size: 1594775,
			isRoot: true,
		},
	},
	{
		text: 'Redis',
		data: {
			name: 'Redis',
			slug: 'redis',
			type: 'redis',
			links: {
				home: 'https://redis.io/',
				code: 'https://github.com/antirez/redis',
			},
			release: '4.0.6',
			mtime: 1515369238,
			db_size: 622165,
			isRoot: true,
		},
	},
	{
		text: 'Redux',
		data: {
			name: 'Redux',
			slug: 'redux',
			type: 'redux',
			links: {
				home: 'http://redux.js.org/',
				code: 'https://github.com/reactjs/redux/',
			},
			release: '3.7.2',
			mtime: 1503762495,
			db_size: 841649,
			isRoot: true,
		},
	},
	{
		text: 'Relay',
		data: {
			name: 'Relay',
			slug: 'relay',
			type: 'simple',
			links: {
				home: 'https://facebook.github.io/relay/',
				code: 'https://github.com/facebook/relay',
			},
			release: '1.4.1',
			mtime: 1507560082,
			db_size: 434956,
			isRoot: true,
		},
	},
	{
		text: 'RequireJS',
		data: {
			name: 'RequireJS',
			slug: 'requirejs',
			type: 'requirejs',
			links: {
				home: 'http://requirejs.org/',
				code: 'https://github.com/requirejs/requirejs',
			},
			release: '2.3.5',
			mtime: 1503762537,
			db_size: 189153,
			isRoot: true,
		},
	},
	{
		text: 'RethinkDB',
		data: {
			name: 'RethinkDB',
			slug: 'rethinkdb~javascript',
			type: 'rethinkdb',
			links: {
				home: 'https://rethinkdb.com/',
				code: 'https://github.com/rethinkdb/rethinkdb',
			},
			version: 'JavaScript',
			release: '2.3.5',
			mtime: 1472417557,
			db_size: 1361322,
			isRoot: true,
		},
		children: [
			{
				text: 'RethinkDB JavaScript',
				data: {
					name: 'RethinkDB',
					slug: 'rethinkdb~javascript',
					type: 'rethinkdb',
					links: {
						home: 'https://rethinkdb.com/',
						code: 'https://github.com/rethinkdb/rethinkdb',
					},
					version: 'JavaScript',
					release: '2.3.5',
					mtime: 1472417557,
					db_size: 1361322,
				},
			},
			{
				text: 'RethinkDB Ruby',
				data: {
					name: 'RethinkDB',
					slug: 'rethinkdb~ruby',
					type: 'rethinkdb',
					links: {
						home: 'https://rethinkdb.com/',
						code: 'https://github.com/rethinkdb/rethinkdb',
					},
					version: 'Ruby',
					release: '2.3.5',
					mtime: 1472417579,
					db_size: 1320925,
				},
			},
			{
				text: 'RethinkDB Python',
				data: {
					name: 'RethinkDB',
					slug: 'rethinkdb~python',
					type: 'rethinkdb',
					links: {
						home: 'https://rethinkdb.com/',
						code: 'https://github.com/rethinkdb/rethinkdb',
					},
					version: 'Python',
					release: '2.3.5',
					mtime: 1472417602,
					db_size: 1326675,
				},
			},
			{
				text: 'RethinkDB Java',
				data: {
					name: 'RethinkDB',
					slug: 'rethinkdb~java',
					type: 'rethinkdb',
					links: {
						home: 'https://rethinkdb.com/',
						code: 'https://github.com/rethinkdb/rethinkdb',
					},
					version: 'Java',
					release: '2.3.5',
					mtime: 1472417625,
					db_size: 1320429,
				},
			},
		],
	},
	{
		text: 'Ruby',
		data: {
			name: 'Ruby',
			slug: 'ruby~2.5',
			type: 'rdoc',
			links: {
				home: 'https://www.ruby-lang.org/',
				code: 'https://github.com/ruby/ruby',
			},
			version: '2.5',
			release: '2.5.0',
			mtime: 1515953941,
			db_size: 7872220,
			isRoot: true,
		},
		children: [
			{
				text: 'Ruby 2.5',
				data: {
					name: 'Ruby',
					slug: 'ruby~2.5',
					type: 'rdoc',
					links: {
						home: 'https://www.ruby-lang.org/',
						code: 'https://github.com/ruby/ruby',
					},
					version: '2.5',
					release: '2.5.0',
					mtime: 1515953941,
					db_size: 7872220,
				},
			},
			{
				text: 'Ruby 2.4',
				data: {
					name: 'Ruby',
					slug: 'ruby~2.4',
					type: 'rdoc',
					links: {
						home: 'https://www.ruby-lang.org/',
						code: 'https://github.com/ruby/ruby',
					},
					version: '2.4',
					release: '2.4.3',
					mtime: 1515953784,
					db_size: 7680468,
				},
			},
			{
				text: 'Ruby 2.3',
				data: {
					name: 'Ruby',
					slug: 'ruby~2.3',
					type: 'rdoc',
					links: {
						home: 'https://www.ruby-lang.org/',
						code: 'https://github.com/ruby/ruby',
					},
					version: '2.3',
					release: '2.3.6',
					mtime: 1515953288,
					db_size: 7522249,
				},
			},
			{
				text: 'Ruby 2.2',
				data: {
					name: 'Ruby',
					slug: 'ruby~2.2',
					type: 'rdoc',
					links: {
						home: 'https://www.ruby-lang.org/',
						code: 'https://github.com/ruby/ruby',
					},
					version: '2.2',
					release: '2.2.9',
					mtime: 1515953093,
					db_size: 7527824,
				},
			},
		],
	},
	{
		text: 'Ruby / Minitest',
		data: {
			name: 'Ruby / Minitest',
			slug: 'minitest',
			type: 'rdoc',
			links: {
				code: 'https://github.com/seattlerb/minitest',
			},
			release: '5.10.3',
			mtime: 1507477106,
			db_size: 194631,
			isRoot: true,
		},
	},
	{
		text: 'Ruby on Rails',
		data: {
			name: 'Ruby on Rails',
			slug: 'rails~5.1',
			type: 'rdoc',
			links: {
				home: 'http://rubyonrails.org/',
				code: 'https://github.com/rails/rails',
			},
			version: '5.1',
			release: '5.1.4',
			mtime: 1507476217,
			db_size: 6221954,
			isRoot: true,
		},
		children: [
			{
				text: 'Ruby on Rails 5.1',
				data: {
					name: 'Ruby on Rails',
					slug: 'rails~5.1',
					type: 'rdoc',
					links: {
						home: 'http://rubyonrails.org/',
						code: 'https://github.com/rails/rails',
					},
					version: '5.1',
					release: '5.1.4',
					mtime: 1507476217,
					db_size: 6221954,
				},
			},
			{
				text: 'Ruby on Rails 5.0',
				data: {
					name: 'Ruby on Rails',
					slug: 'rails~5.0',
					type: 'rdoc',
					links: {
						home: 'http://rubyonrails.org/',
						code: 'https://github.com/rails/rails',
					},
					version: '5.0',
					release: '5.0.6',
					mtime: 1507476078,
					db_size: 6141087,
				},
			},
			{
				text: 'Ruby on Rails 4.2',
				data: {
					name: 'Ruby on Rails',
					slug: 'rails~4.2',
					type: 'rdoc',
					links: {
						home: 'http://rubyonrails.org/',
						code: 'https://github.com/rails/rails',
					},
					version: '4.2',
					release: '4.2.10',
					mtime: 1507476395,
					db_size: 5525311,
				},
			},
			{
				text: 'Ruby on Rails 4.1',
				data: {
					name: 'Ruby on Rails',
					slug: 'rails~4.1',
					type: 'rdoc',
					links: {
						home: 'http://rubyonrails.org/',
						code: 'https://github.com/rails/rails',
					},
					version: '4.1',
					release: '4.1.16',
					mtime: 1483393875,
					db_size: 3792537,
				},
			},
		],
	},
	{
		text: 'Rust',
		data: {
			name: 'Rust',
			slug: 'rust',
			type: 'rust',
			links: {
				home: 'https://www.rust-lang.org/',
				code: 'https://github.com/rust-lang/rust',
			},
			release: '1.24.0',
			mtime: 1519573923,
			db_size: 38777581,
			isRoot: true,
		},
	},
	{
		text: 'Sass',
		data: {
			name: 'Sass',
			slug: 'sass',
			type: 'yard',
			links: {
				home: 'http://sass-lang.com/',
				code: 'https://github.com/sass/sass',
			},
			release: '3.5.3',
			mtime: 1509303125,
			db_size: 205046,
			isRoot: true,
		},
	},
	{
		text: 'scikit-image',
		data: {
			name: 'scikit-image',
			slug: 'scikit_image',
			type: 'sphinx',
			links: {
				home: 'http://scikit-image.org/',
				code: 'https://github.com/scikit-image/scikit-image',
			},
			release: '0.13.1',
			mtime: 1509303151,
			db_size: 2167707,
			isRoot: true,
		},
	},
	{
		text: 'scikit-learn',
		data: {
			name: 'scikit-learn',
			slug: 'scikit_learn',
			type: 'sphinx',
			links: {
				home: 'http://scikit-learn.org/',
				code: 'https://github.com/scikit-learn/scikit-learn',
			},
			release: '0.19.1',
			mtime: 1509303678,
			db_size: 47201336,
			isRoot: true,
		},
	},
	{
		text: 'Sinon.JS',
		data: {
			name: 'Sinon.JS',
			slug: 'sinon~4',
			type: 'sinon',
			links: {
				home: 'http://sinonjs.org/',
				code: 'https://github.com/sinonjs/sinon',
			},
			version: '4',
			release: '4.4.2',
			mtime: 1519573757,
			db_size: 101247,
			isRoot: true,
		},
		children: [
			{
				text: 'Sinon.JS 4',
				data: {
					name: 'Sinon.JS',
					slug: 'sinon~4',
					type: 'sinon',
					links: {
						home: 'http://sinonjs.org/',
						code: 'https://github.com/sinonjs/sinon',
					},
					version: '4',
					release: '4.4.2',
					mtime: 1519573757,
					db_size: 101247,
				},
			},
			{
				text: 'Sinon.JS 3',
				data: {
					name: 'Sinon.JS',
					slug: 'sinon~3',
					type: 'sinon',
					links: {
						home: 'http://sinonjs.org/',
						code: 'https://github.com/sinonjs/sinon',
					},
					version: '3',
					release: '3.3.0',
					mtime: 1506272828,
					db_size: 105244,
				},
			},
			{
				text: 'Sinon.JS 2',
				data: {
					name: 'Sinon.JS',
					slug: 'sinon~2',
					type: 'sinon',
					links: {
						home: 'http://sinonjs.org/',
						code: 'https://github.com/sinonjs/sinon',
					},
					version: '2',
					release: '2.4.1',
					mtime: 1506272828,
					db_size: 96240,
				},
			},
			{
				text: 'Sinon.JS 1',
				data: {
					name: 'Sinon.JS',
					slug: 'sinon~1',
					type: 'sinon',
					links: {
						home: 'http://sinonjs.org/',
						code: 'https://github.com/sinonjs/sinon',
					},
					version: '1',
					release: '1.17.7',
					mtime: 1506272829,
					db_size: 83926,
				},
			},
		],
	},
	{
		text: 'Socket.IO',
		data: {
			name: 'Socket.IO',
			slug: 'socketio',
			type: 'socketio',
			links: {
				home: 'http://socket.io/',
				code: 'https://github.com/socketio/socket.io',
			},
			release: '1.4.5',
			mtime: 1461429367,
			db_size: 44110,
			isRoot: true,
		},
	},
	{
		text: 'SQLite',
		data: {
			name: 'SQLite',
			slug: 'sqlite',
			type: 'sqlite',
			links: {
				home: 'https://sqlite.org/',
				code: 'https://www.sqlite.org/src/',
			},
			release: '3.22.0',
			mtime: 1519573990,
			db_size: 11698957,
			isRoot: true,
		},
	},
	{
		text: 'Statsmodels',
		data: {
			name: 'Statsmodels',
			slug: 'statsmodels',
			type: 'sphinx',
			links: {
				home: 'http://www.statsmodels.org/',
				code: 'https://github.com/statsmodels/statsmodels/',
			},
			release: '0.8.0',
			mtime: 1495472273,
			db_size: 13455712,
			isRoot: true,
		},
	},
	{
		text: 'Support Tables',
		data: {
			name: 'Support Tables',
			slug: 'browser_support_tables',
			type: 'support_tables',
			mtime: 1519574284,
			db_size: 26357539,
			isRoot: true,
		},
	},
	{
		text: 'SVG',
		data: {
			name: 'SVG',
			slug: 'svg',
			type: 'mdn',
			mtime: 1515963636,
			db_size: 1758691,
			isRoot: true,
		},
	},
	{
		text: 'Symfony',
		data: {
			name: 'Symfony',
			slug: 'symfony~4.0',
			type: 'laravel',
			links: {
				home: 'https://symfony.com/',
				code: 'https://github.com/symfony/symfony',
			},
			version: '4.0',
			release: '4.0.3',
			mtime: 1515369903,
			db_size: 14182389,
			isRoot: true,
		},
		children: [
			{
				text: 'Symfony 4.0',
				data: {
					name: 'Symfony',
					slug: 'symfony~4.0',
					type: 'laravel',
					links: {
						home: 'https://symfony.com/',
						code: 'https://github.com/symfony/symfony',
					},
					version: '4.0',
					release: '4.0.3',
					mtime: 1515369903,
					db_size: 14182389,
				},
			},
			{
				text: 'Symfony 3.4',
				data: {
					name: 'Symfony',
					slug: 'symfony~3.4',
					type: 'laravel',
					links: {
						home: 'https://symfony.com/',
						code: 'https://github.com/symfony/symfony',
					},
					version: '3.4',
					release: '3.4.3',
					mtime: 1515369763,
					db_size: 14949752,
				},
			},
			{
				text: 'Symfony 3.3',
				data: {
					name: 'Symfony',
					slug: 'symfony~3.3',
					type: 'laravel',
					links: {
						home: 'https://symfony.com/',
						code: 'https://github.com/symfony/symfony',
					},
					version: '3.3',
					release: '3.3.15',
					mtime: 1515369628,
					db_size: 14066834,
				},
			},
			{
				text: 'Symfony 3.2',
				data: {
					name: 'Symfony',
					slug: 'symfony~3.2',
					type: 'laravel',
					links: {
						home: 'https://symfony.com/',
						code: 'https://github.com/symfony/symfony',
					},
					version: '3.2',
					release: '3.2.13',
					mtime: 1509304300,
					db_size: 13318281,
				},
			},
			{
				text: 'Symfony 3.1',
				data: {
					name: 'Symfony',
					slug: 'symfony~3.1',
					type: 'laravel',
					links: {
						home: 'https://symfony.com/',
						code: 'https://github.com/symfony/symfony',
					},
					version: '3.1',
					release: '3.1.8',
					mtime: 1509304394,
					db_size: 12851145,
				},
			},
			{
				text: 'Symfony 3.0',
				data: {
					name: 'Symfony',
					slug: 'symfony~3.0',
					type: 'laravel',
					links: {
						home: 'https://symfony.com/',
						code: 'https://github.com/symfony/symfony',
					},
					version: '3.0',
					release: '3.0.1',
					mtime: 1509304485,
					db_size: 12691338,
				},
			},
			{
				text: 'Symfony 2.8',
				data: {
					name: 'Symfony',
					slug: 'symfony~2.8',
					type: 'laravel',
					links: {
						home: 'https://symfony.com/',
						code: 'https://github.com/symfony/symfony',
					},
					version: '2.8',
					release: '2.8.28',
					mtime: 1509304582,
					db_size: 13046428,
				},
			},
			{
				text: 'Symfony 2.7',
				data: {
					name: 'Symfony',
					slug: 'symfony~2.7',
					type: 'laravel',
					links: {
						home: 'https://symfony.com/',
						code: 'https://github.com/symfony/symfony',
					},
					version: '2.7',
					release: '2.7.35',
					mtime: 1509304675,
					db_size: 12438508,
				},
			},
		],
	},
	{
		text: 'Tcl/Tk',
		data: {
			name: 'Tcl/Tk',
			slug: 'tcl_tk',
			type: 'tcl_tk',
			release: '8.6.6',
			mtime: 1471816808,
			db_size: 3268853,
			isRoot: true,
		},
	},
	{
		text: 'TensorFlow',
		data: {
			name: 'TensorFlow',
			slug: 'tensorflow~python',
			type: 'tensorflow',
			links: {
				home: 'https://www.tensorflow.org/',
				code: 'https://github.com/tensorflow/tensorflow',
			},
			version: 'Python',
			release: '1.6',
			mtime: 1521395225,
			db_size: 15293134,
			isRoot: true,
		},
		children: [
			{
				text: 'TensorFlow Python',
				data: {
					name: 'TensorFlow',
					slug: 'tensorflow~python',
					type: 'tensorflow',
					links: {
						home: 'https://www.tensorflow.org/',
						code: 'https://github.com/tensorflow/tensorflow',
					},
					version: 'Python',
					release: '1.6',
					mtime: 1521395225,
					db_size: 15293134,
				},
			},
			{
				text: 'TensorFlow C++',
				data: {
					name: 'TensorFlow',
					slug: 'tensorflow~cpp',
					type: 'tensorflow',
					links: {
						home: 'https://www.tensorflow.org/',
						code: 'https://github.com/tensorflow/tensorflow',
					},
					version: 'C++',
					release: '1.6',
					mtime: 1521396425,
					db_size: 4525901,
				},
			},
			{
				text: 'TensorFlow Guide',
				data: {
					name: 'TensorFlow',
					slug: 'tensorflow~guide',
					type: 'tensorflow',
					links: {
						home: 'https://www.tensorflow.org/',
						code: 'https://github.com/tensorflow/tensorflow',
					},
					version: 'Guide',
					release: '1.6',
					mtime: 1521396499,
					db_size: 9854630,
				},
			},
		],
	},
	{
		text: 'Twig',
		data: {
			name: 'Twig',
			slug: 'twig~2',
			type: 'sphinx',
			links: {
				home: 'https://twig.sensiolabs.org/',
				code: 'https://github.com/twigphp/Twig',
			},
			version: '2',
			release: '2.4.3',
			mtime: 1498404313,
			db_size: 313095,
			isRoot: true,
		},
		children: [
			{
				text: 'Twig 2',
				data: {
					name: 'Twig',
					slug: 'twig~2',
					type: 'sphinx',
					links: {
						home: 'https://twig.sensiolabs.org/',
						code: 'https://github.com/twigphp/Twig',
					},
					version: '2',
					release: '2.4.3',
					mtime: 1498404313,
					db_size: 313095,
				},
			},
			{
				text: 'Twig 1',
				data: {
					name: 'Twig',
					slug: 'twig~1',
					type: 'sphinx',
					links: {
						home: 'https://twig.sensiolabs.org/',
						code: 'https://github.com/twigphp/Twig',
					},
					version: '1',
					release: '1.34.3',
					mtime: 1498404317,
					db_size: 337425,
				},
			},
		],
	},
	{
		text: 'TypeScript',
		data: {
			name: 'TypeScript',
			slug: 'typescript',
			type: 'typescript',
			links: {
				home: 'https://www.typescriptlang.org',
				code: 'https://github.com/Microsoft/TypeScript',
			},
			release: '2.7.2',
			mtime: 1519584580,
			db_size: 1259430,
			isRoot: true,
		},
	},
	{
		text: 'Underscore.js',
		data: {
			name: 'Underscore.js',
			slug: 'underscore',
			type: 'underscore',
			release: '1.8.3',
			mtime: 1460208506,
			db_size: 56452,
			isRoot: true,
		},
	},
	{
		text: 'Vagrant',
		data: {
			name: 'Vagrant',
			slug: 'vagrant',
			type: 'vagrant',
			links: {
				home: 'https://www.vagrantup.com/',
				code: 'https://github.com/mitchellh/vagrant',
			},
			release: '2.0.2',
			mtime: 1519584828,
			db_size: 561843,
			isRoot: true,
		},
	},
	{
		text: 'Vue.js',
		data: {
			name: 'Vue.js',
			slug: 'vue~2',
			type: 'vue',
			links: {
				home: 'https://vuejs.org/',
				code: 'https://github.com/vuejs/vue',
			},
			version: '2',
			release: '2.5.13',
			mtime: 1515369919,
			db_size: 811609,
			isRoot: true,
		},
		children: [
			{
				text: 'Vue.js 2',
				data: {
					name: 'Vue.js',
					slug: 'vue~2',
					type: 'vue',
					links: {
						home: 'https://vuejs.org/',
						code: 'https://github.com/vuejs/vue',
					},
					version: '2',
					release: '2.5.13',
					mtime: 1515369919,
					db_size: 811609,
				},
			},
			{
				text: 'Vue.js 1',
				data: {
					name: 'Vue.js',
					slug: 'vue~1',
					type: 'vue',
					links: {
						home: 'https://vuejs.org/',
						code: 'https://github.com/vuejs/vue',
					},
					version: '1',
					release: '1.0.28',
					mtime: 1491756620,
					db_size: 272329,
				},
			},
		],
	},
	{
		text: 'Vulkan',
		data: {
			name: 'Vulkan',
			slug: 'vulkan',
			type: 'vulkan',
			links: {
				home: 'https://www.khronos.org/vulkan/',
			},
			release: '1.0.59',
			mtime: 1504468140,
			db_size: 1797883,
			isRoot: true,
		},
	},
	{
		text: 'webpack',
		data: {
			name: 'webpack',
			slug: 'webpack',
			type: 'webpack',
			links: {
				home: 'https://webpack.js.org/',
				code: 'https://github.com/webpack/webpack',
			},
			version: '',
			release: '4.2.0',
			mtime: 1521915307,
			db_size: 1112463,
			isRoot: true,
		},
		children: [
			{
				text: 'webpack',
				data: {
					name: 'webpack',
					slug: 'webpack',
					type: 'webpack',
					links: {
						home: 'https://webpack.js.org/',
						code: 'https://github.com/webpack/webpack',
					},
					version: '',
					release: '4.2.0',
					mtime: 1521915307,
					db_size: 1112463,
				},
			},
			{
				text: 'webpack 1',
				data: {
					name: 'webpack',
					slug: 'webpack~1',
					type: 'webpack',
					links: {
						home: 'https://webpack.github.io/',
						code: 'https://github.com/webpack/webpack/tree/webpack-1',
					},
					version: '1',
					release: '1.15.0',
					mtime: 1506273002,
					db_size: 848140,
				},
			},
		],
	},
	{
		text: 'XSLT & XPath',
		data: {
			name: 'XSLT & XPath',
			slug: 'xslt_xpath',
			type: 'mdn',
			mtime: 1506194497,
			db_size: 212683,
			isRoot: true,
		},
	},
	{
		text: 'Yarn',
		data: {
			name: 'Yarn',
			slug: 'yarn',
			type: 'yarn',
			links: {
				home: 'https://yarnpkg.com/',
				code: 'https://github.com/yarnpkg/yarn',
			},
			release: '1.5.1',
			mtime: 1521385614,
			db_size: 178831,
			isRoot: true,
		},
	},
	{
		text: 'Yii',
		data: {
			name: 'Yii',
			slug: 'yii~2.0',
			type: 'yii',
			links: {
				home: 'http://www.yiiframework.com/',
				code: 'https://github.com/yiisoft/yii2',
			},
			version: '2.0',
			release: '2.0.12',
			mtime: 1498404939,
			db_size: 15399034,
			isRoot: true,
		},
		children: [
			{
				text: 'Yii 2.0',
				data: {
					name: 'Yii',
					slug: 'yii~2.0',
					type: 'yii',
					links: {
						home: 'http://www.yiiframework.com/',
						code: 'https://github.com/yiisoft/yii2',
					},
					version: '2.0',
					release: '2.0.12',
					mtime: 1498404939,
					db_size: 15399034,
				},
			},
			{
				text: 'Yii 1.1',
				data: {
					name: 'Yii',
					slug: 'yii~1.1',
					type: 'yii',
					links: {
						home: 'http://www.yiiframework.com/',
						code: 'https://github.com/yiisoft/yii',
					},
					version: '1.1',
					release: '1.1.19',
					mtime: 1498404499,
					db_size: 13150704,
				},
			},
		],
	},
];

export default {
	data() {
		return {
			releaseTrees: treeData,
		};
	},
	components: {
		liquorTree: LiquorTree,
	},
	methods: {
		onTreeMounted(tree) {
			tree.sortTree('asc', true);
		},
	},
};
</script>

<style>
.wrapper .tree-arrow {
	margin-left: 0px;
}
</style>
